### ISSUE TITLE
ModelNotCompliantException in UserVerification.php line 81:

### ISSUE THREAD

**Issue by renege** [jrean/laravel-user-verification#10]
Hi, 
What is missing if I get: The model instance provided is not compliant with this package. ? Thats not clear from docs.

**Comment by jrean** [comment]
Hi @renege 
The documentation says:

> Prior to use this package the table representing the user must be updated with two new columns, "verified" and "verification_token". It is mandatory to add the two columns on the same table and where the user's email is stored. Last but not least, the model must implement the authenticatable interface Illuminate\Contracts\Auth\Authenticatable which is the default with the Eloquent User model.

Follow the documentation and update the table representing your user with the migration steps provided. If the table doesn't contain the "verified" and "verification_token" columns the package with throw the `ModelNotCompliantException`.

Please try and tell us.

Cheers,
