### ISSUE TITLE
Not working with MongoDB

### ISSUE THREAD

**Issue by xparthxvorax** [jrean/laravel-user-verification#100]
Set up fresh Laravel 5.3 with MongoDB (https://github.com/jenssegers/laravel-mongodb)

Clicking on verification link from the verification email gives:

```
ErrorException in UserVerification.php line 255:
Attempt to assign property of non-object
```
Note: Package has configured properly as per the documentation.

**Comment by jrean** [comment]
Yes.
The current package version won’t work with MongoDb because it returns and array instead of an object.
It will be patched in the next upcoming release.

Sorry about that.

**Comment by xparthx** [comment]
Thanks for your quick reply.

Can I know ETA for the next upcoming release?

**Comment by jrean** [comment]
It will come with the 4.1 release (under writing) and unfortunately, I can't provide a precise ETA.
It will be back-ported to the 3.1 update as well.

**Comment by darvindom** [comment]
I get same issue on mongoDB.
just edit in class 
    /**
     * Get the user by e-mail.
     *
     * @param  string  $email
     * @param  string  $table
     * @return stdClass
     *
     * @throws \Jrean\UserVerification\Exceptions\UserNotFoundException
     */
    protected function getUserByEmail($email, $table)
    {
        $user = DB::table($table)
            ->where('email', $email)
            ->first();

        if ($user === null) {
            throw new UserNotFoundException();
        }
        $user = (object)$user;
        $user->table = $table;

        return $user;
    }

**Comment by FM1337** [comment]
So we're currently past the 4.1 release and this issue still happens.
