### ISSUE TITLE
Composer not working!

### ISSUE THREAD

**Issue by EazyServer** [jrean/laravel-user-verification#104]
Any idea why I get this error?

Thanks
![target](https://cloud.githubusercontent.com/assets/19202935/22747679/a6abafee-ee1f-11e6-9341-144810e201b6.png)

**Comment by jrean** [comment]
Because it seems you are trying to install the 4.0.1 version of the package with the 5.3 version of Laravel?

5.3.x => 3.0.x
5.4.x => 4.0.x

**Comment by EazyServer** [comment]
That was the issue indeed! Thanks for your help.

For anyone stumbling upon this you can use

`composer require jrean/laravel-user-verification 3.0.19`

**Comment by jrean** [comment]
:-)

composer require ... ^3.0.*
(For Laravel 5.3.x)
