### ISSUE TITLE
User Verification with Spark?

### ISSUE THREAD

**Issue by gstoa** [jrean/laravel-user-verification#107]
Any success or how-to's leveraging this great package with Laravel 5.4 and Spark?  Spark's registration process adds quite a bit of twists to the standard Laravel install, but I'd love to not have to write user email verification from scratch and use this package if possible.

**Comment by ianfagg** [comment]
I really need this too! Wish I was good enough to tackle it myself! May have to roll up my sleeves and try because I'm desperate. If you read this Taylor please give jrean a lifetime license for Spark if they solve it!

**Comment by jrean** [comment]
@ianfagg thank you for the feedback.
I already sent an e-mail to Taylor to request a "test license" but he never replied.

**Comment by ianfagg** [comment]
Oh, that's a shame. I would have thought it was in his interest to do that, and costs him nothing!

I've bought Spark for my project and a bit miffed it does not have this feature. If I solve it based on your package I'll see if I can do a pull request (never done that before) to see if it can be added.

I'm definitely going to try your package for other projects too, it's a must have in my opinion. Thanks for sharing.

All the best, Ian

**Comment by ianfagg** [comment]
I've almost got this working with Spark now, but where the documentation says:

Attributes/Properties
To customize the package behaviour and the redirects you can implement and customize six (6) attributes/properties:

Sorry for my ignorance but where and how do I do that without overwriting the source files?

Thanks very much, Ian

**Comment by jrean** [comment]
Hi.
Awesome!
The attributes can be declared where you call the "traits". In the controller :-)

**Comment by ianfagg** [comment]
Thanks @jrean so I've added $this->redirectAfterVerification = '/login'; to the __construct of my RegisterController and that's working. However I'd like to be able to flash a message to the user to confirm they have been verified correctly. Any ideas how I could do that?

**Comment by jrean** [comment]
Sure!
Use the event :-)
UserVerified.php
Create a listener and do what you want.

Jean

**Comment by ianfagg** [comment]
Of course, sorry, I'm an idiot!

I'll get onto that now, then I'll write up what I've had to do to get this working with Spark and forward it to you. I think it's pretty straight forward actually (although it's taken me days of trial and error because I don't know what I'm doing!).

Thanks again,

Ian

**Comment by jrean** [comment]
It would be much appreciated :-)
If you want go to https://askjong.com/contact/jong
Drop me a message so we can exchange by e-mail.

**Comment by ianfagg** [comment]
OK, will do.

**Comment by jrean** [comment]
@ianfagg any news?
:-)

**Comment by hltky** [comment]
@jrean any word from @ianfagg yet on the spark implementation?

**Comment by ianfagg** [comment]
Sorry, been distracted by a couple of 'paid' projects. But hopefully get back onto it in the next week or so. I got it working as far as I remember, but was hoping to go live with the project to be sure. So need to check it through and write it up. I'll let you know...

**Comment by gnullByte** [comment]
Happy to have found this. Thanks for the write-up!

**Comment by jrean** [comment]
Thank you @ianfagg 
I added a section in the documentation mentioning your article.
