### ISSUE TITLE
Routes not overrides

### ISSUE THREAD

**Issue by ZapevalovAnton** [jrean/laravel-user-verification#109]
I added my custom routes with the same names in routes.php, but they not overrides.

**Comment by jrean** [comment]
Please provide more details.
Laravel version / Package version
+ code sample.

Thanks

**Comment by ZapevalovAnton** [comment]
"laravel/framework": "5.4.*",
"jrean/laravel-user-verification": "^4.0"

```
Route::get('email-verification/error', [
    'as' => 'email-verification.error',
    'uses' => 'UserController@getVerificationError'
]);

Route::get('email-verification/check/{token}', [
  'as'   => 'email-verification.check',
  'uses' => 'UserController@getVerification'
]);
```

I want use UserController for verification.

![image](https://cloud.githubusercontent.com/assets/6674242/23455481/8eb2a4ec-fe91-11e6-8c63-3e87f55f28fc.png)

**Comment by jrean** [comment]
Please share your UserController class.

**Comment by ZapevalovAnton** [comment]
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use Auth;
use App\User;

use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class UserController extends Controller
{
    use VerifiesUsers;

    public function create(Request $request) {

        $this->validate($request, [
            'name'  => 'required',
            'email' => 'required|email',
        ]);

        $user = User::create($request->all());

        $user->account_id = Auth::user()->account_id;

        $user->save();

        UserVerification::generate($user);

        UserVerification::send($user, 'Регистрация на сайте TestTestTest');

        return redirect()->back()->with('status', 'Пользователю отправлено сообщение на почту, для завершения регистрации.');
    }


    public function settings($id) {
        $user = User::find($id);

        if(!$user) abort(404);

        return view('users.settings', ['user' => $user]);
    }
}
```

**Comment by jrean** [comment]
@ZapevalovAnton can you please try the following:

Add the package service provider BEFORE the app RouteServiceProvider in the `config.php` file.

Please tell me if it fixes your issue.

**Comment by ZapevalovAnton** [comment]
Yes, it fixed!

**Comment by jrean** [comment]
Ok. This functionality came from a PR and it seems the Doc hasn't been updated properly. I'll fix it. Thank you for reporting the issue.

**Comment by ngugijames** [comment]
As an addition, prefixing your routes with anything will also produce this error. I had placed these routes in a group with a custom prefix and I have wasted a lot of time trying to solve this error.

**Comment by jrean** [comment]
Do you have suggestions?
