### ISSUE TITLE
Mailable availability (4.1)

### ISSUE THREAD

**Issue by ockam** [jrean/laravel-user-verification#111]
Hi Jean, thank you for this great package.

I don’t mean to put any pressure on you but do you have an approximate date when mailable (4.1) will be available? I want to know if I wait for it for my current project. :)

**Comment by josiasmontag** [comment]
I had the same issue recently. Because of other fundamental mismatches of this package for my use case (Events, crypto-based tokens), I decided to write a new email verification [package](https://github.com/josiasmontag/laravel-email-verification) from scratch.  Maybe this helps you.

**Comment by jrean** [comment]
@josiasmontag Why not to contribute to this package instead of making your own...
@ockam I will work on it this weekend.

**Comment by josiasmontag** [comment]
@jrean Mine is using crypto-based verification which is fundamental different from your approach using database persisted tokens. I don't think it is practical and desired to change this package so radical. However, feel free to port the other changes (Notifcations, Events) to your package.

**Comment by jrean** [comment]
> I don't think it is practical ...

Instead of assuming you should have suggested. It's the core principle of open source projects. Isn't?
Your approach is more than welcome. I will dig into your implementation and see how/what we can merge.

Thanks :-)

**Comment by jrean** [comment]
@ockam 
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.0
