### ISSUE TITLE
Verified Event 

### ISSUE THREAD

**Issue by EazyServer** [jrean/laravel-user-verification#112]
Is there any event fired when user verified?

**Comment by EazyServer** [comment]
I have just dug down and could not find any event fired on verified. I will add PR to this!

**Comment by markdegrootnl** [comment]
Please add this. PR #113 looks great

**Comment by jrean** [comment]
@EazyServer thank you.
https://github.com/jrean/laravel-user-verification/releases/tag/v4.0.2
