### ISSUE TITLE
Override the routes before they getting loaded

### ISSUE THREAD

**Issue by Konafets** [jrean/laravel-user-verification#115]
Hi,

I am working on a project where the vendor name – which is `App` by default – was overwritten by a custom name `Foo`. Therefore the route `App\Http\Controllers\Auth\RegisterController` does not exists, but `Foo\Http\Controllers\Auth\RegisterController` and throws an error. 

How can I override the routes defined by this ServiceProvider?

**Comment by Konafets** [comment]
Just for the record. I extended the package ServiceProvider and adjusted the routes within `boot()` method and called my SP in `app.php`.

**Comment by jrean** [comment]
@Konafets 

The way to go is the following:
Put the package service provider call BEFORE the `RouteServiceProvider` call

```
        /*
         * Package Service Providers...
         */
        Jrean\UserVerification\UserVerificationServiceProvider::class,
  
        /*
         * Application Service Providers...
         */
        // ...
        App\Providers\RouteServiceProvider::class,
```

Then in your route file, you can declare your custom routes (with the same name) and it will override ;-)

Hope it will help you.

https://github.com/jrean/laravel-user-verification/issues/109

**Comment by Konafets** [comment]
@jrean Thanks for your answer. That helped indeed.

**Comment by alexeydemin** [comment]
Web part works perfect, but 
`php artisan route:list` command still outputs:
```
[ReflectionException]
Class App\Http\Controllers\Auth\RegisterController does not exist
```

**Comment by guicara** [comment]
Hello,

I face the same problem with the `php artisan route:list` command.
Is it possible to fix that?

**Comment by jrean** [comment]
@guicara,

Thanks for sharing your feedback.
Removing the auto discovery, *Yes*.
I don't know how you did it but a convenient way is to add a few lines to your own project `composer.json` file such as:

```
"extra": {
    "laravel": {
        "dont-discover": [
            "jrean/laravel-user-verification"
        ]
    }
},
```

Extending the package to remove the route loading, *No*.

Put the package service provider call BEFORE the `RouteServiceProvider` call:

```
        /*
         * Package Service Providers...
         */
        Jrean\UserVerification\UserVerificationServiceProvider::class,
  
        /*
         * Application Service Providers...
         */
        // ...
        App\Providers\RouteServiceProvider::class,
```

Then in your route file, you can declare your custom routes (with the same name) and it will override the one from the package.

**Comment by jrean** [comment]
@guicara what do you mean it only works for the web part?
I cannot reproduce the:

```
[ReflectionException]
Class App\Http\Controllers\Auth\RegisterController does not exist
```

With `php artisan route:list` command.

On my side, it outputs the routes available with no error.

**Comment by guicara** [comment]
After performing some tests, I cannot correctly ovverride the packages routes, because I'm using https://github.com/nWidart/laravel-modules/. So please forgot what I said earlier.
