### ISSUE TITLE
Verification doesn't work on server, but works on localhost

### ISSUE THREAD

**Issue by baturaykaya** [jrean/laravel-user-verification#117]
Hello,

I tested the package in my laptop using localhost and it worked. However, on my DigitalOcean droplet, it won't work. 

The problem is, after user clicks to the verification link, user's email from the request returns null. Please see my getVerification fn below:

```
public function getVerification(Request $request, $token)
    {
        $this->validateRequest($request);
        try {
            UserVerificationFacade::process($request->input('email'), $token, $this->userTable());
        } catch (UserNotFoundException $e) {
            return redirect($this->redirectIfVerificationFails());
        } catch (UserIsVerifiedException $e) {
            return redirect($this->redirectIfVerified());
        } catch (TokenMismatchException $e) {
            return redirect($this->redirectIfVerificationFails());
        }
        return redirect($this->redirectAfterVerification());
    }
```

When I `dd($request)`, it has only 1 parameter which is `query_string = null`. And the exception I got is:

UserNotFoundException in UserVerification.php line 202:
No user found for the given email address.

Thx, I need your help

**Comment by jrean** [comment]
Hi,

What version of Laravel and Package do you use?
Please follow the documentation **step by step** and it should work out of the box.

**Comment by jrean** [comment]
@baturaykaya please update the package with composer. I just released a few updates.

It seems that your verification link doesn't contains the `email` parameter. Have you checked?
Are you sure your user has an e-mail property not null or empty?

**Comment by Konafets** [comment]
I can reproduce this error. Valdidating worked with 4.1.1 but not with 4.1.3.

**Comment by jrean** [comment]
@baturaykaya @Konafets 
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.4

**Comment by baturaykaya** [comment]
Sorry for my late response. The problem was with nginx configuration.
