### ISSUE TITLE
Branch 2.2 Selects random user if no email given

### ISSUE THREAD

**Issue by judgej** [jrean/laravel-user-verification#118]
I'm on 2.2 due to the version of laravel I'm using. This may not be a problem in other branches, but I'm raising it while I remember, and will add further details when I can.

I updated a site that was using 2.x and it seems that the email on the verification URL is a new requirement, which my verification email template did not include. Tracing through the code (since users were all getting "verification has failed" errors), a user *was* selected from the database. However, it was not the correct user - it was just the first user that came out of the users table. This was of course failing the verification since that was not the user being verified, but the fact that it got that user means the reason for failure can be misleading.

Instead, if no email is given in the verification URL, the verification process should realise that earlier, *not* go and fetch a user with the missing email address, and go down the "user not found" path.

I don't believe this is a security issue, but just the fact that it is possible for the verification process to be even *looking* at the wrong user could lead to unexpected consequences.

**Comment by judgej** [comment]
Whether people being able to manipulate the email in the URL can be used to expose some information on the users in the system, is another question, I guess.

**Comment by judgej** [comment]
This may also have happened to me because I have users without emails. These are users imported from another offline system, and are being contacted through other channels to get their email addresses, so are perfectly valid blank emails.

**Comment by judgej** [comment]
The [ValidateRequest](https://github.com/jrean/laravel-user-verification/blob/2.2/src/Traits/VerifiesUsers.php#L59) function does return a redirect if the email is missing or not an email.

However, where it is called in [getVerification](https://github.com/jrean/laravel-user-verification/blob/2.2/src/Traits/VerifiesUsers.php#L28) does not do anything with that result, so a missing or invalid email is completely ignored. I think *this* is the core of the problem and where it needs to be fixed.

**Comment by jrean** [comment]
@judgej thank you for your feedback. I read carefully your notes.

```
    /**
     * Handle the user verification.
     *
     * @param  string  $token
     * @return Response
     */
    public function getVerification(Request $request, $token)
    {
        $this->validateRequest($request);

        try {
            UserVerification::process($request->input('email'), $token, $this->userTable());
        } catch (UserNotFoundException $e) {
            return redirect($this->redirectIfVerificationFails());
        } catch (UserIsVerifiedException $e) {
            return redirect($this->redirectIfVerified());
        } catch (TokenMismatchException $e) {
            return redirect($this->redirectIfVerificationFails());
        }

        return redirect($this->redirectAfterVerification());
    }
```

As you can see, before anything `$this->validateRequest($request);` is called.

```
    /**
     * Validate the verification link.
     *
     * @param  string  $token
     * @return Response
     */
    protected function validateRequest(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email'
        ]);

        if ($validator->fails()) {
            return redirect($this->redirectIfVerificationFails());
        }
    }
```

As you can see the `email` parameter is `required` and must be an `email`.

So it means if the verification link is either something like:
- `http://52.dev/verification/TOKEN?email=` or
- `http://52.dev/verification/TOKEN` or
- `http://52.dev/verification/TOKEN?email=null` or

**then the verification will simply fail and the package will return (and display) the error view.**

The following code never be executed in that case!

```
  try {
            UserVerification::process($request->input('email'), $token, $this->userTable());
        } catch (UserNotFoundException $e) {
            return redirect($this->redirectIfVerificationFails());
        } catch (UserIsVerifiedException $e) {
            return redirect($this->redirectIfVerified());
        } catch (TokenMismatchException $e) {
            return redirect($this->redirectIfVerificationFails());
        }
```

So I'm not really sure to understand your point. How could I check that before as it is already the very first thing tested?

My question is more on your side; Why would you like to "verify" a user who doesn't have an e-mail. It sounds like a task which is out of the scope of this package.

The only thing I could add is a test on the `public function generate(AuthenticatableContract $user)` that throws an exception if a user doesn't have an email.

If you think I miss understood your point, please share it again.

**Comment by judgej** [comment]
The `validateRequest` returns a redirect object. It does not do a redirect, it just returns the object.

The `getVerification` calls `validateRequest` which returns the object. But what does it do with the object? Nothing. The return from `validateRequest` is not assigned to any variable, and not returned to `getVerification`'s caller, so the redirect object is just discarded. The process just carries on as though no error happened.

**Comment by jrean** [comment]
> The validateRequest returns a redirect object. It does not do a redirect, it just returns the object.

??

```
        if ($validator->fails()) {
            return redirect($this->redirectIfVerificationFails());
        }
```

It calls the `redirect()` helper from laravel giving as parameter the url to target that can be found into the included traits.

```
    /**
     * Get the redirect path for a failing verification token verification.
     *
     * @return string
     */
    public function redirectIfVerificationFails()
    {
        return property_exists($this, 'redirectIfVerificationFails') ? $this->redirectIfVerificationFails : '/verification/error';
    }
```

So in that case it will `redirect` to the following URL `/verification/error` which is handled by default by the package `Route::get('verification/error', 'Auth\AuthController@getVerificationError');`.

If you think I miss understood your point, please share it again because I still don't get it.

**Comment by jrean** [comment]
What version of Laravel do you use @judgej ?

**Comment by judgej** [comment]
Here: https://laravel.com/docs/5.4/helpers#method-redirect

The helper just returns a redirect response. A redirect response is just an object. If you don't do anything with that object, then nothing happens. That object needs to be passed on to the request handler for the request handler so say, "oh, you want me to redirect".

**Comment by judgej** [comment]
This site is a 5.1 instance. Will update it at some point, but that's a future exercise.

**Comment by jrean** [comment]
You seem to miss understand how the `redirect()` helper is working in Laravel.
I performed tests on 5.0.x / 5.1.x / 5.2.x with the version 2.2.x of this package and everything is working properly.

Feel free to send a pull request.

**Comment by judgej** [comment]
That's a bit worrying. My understanding matches the evidence I am seeing in production, and matches the laravel documentation I linked to.

What do you think happens when you `return` from a method with any kind of value? It returns that value to the caller. If the caller does not use that value, what do you think happens to it? This is PHP at its most basic, not laravel magic.

**Comment by jrean** [comment]
https://github.com/laravel/framework/blob/78b3fe6bdc6d8219c4b6aca5a160e27c9e65b3d8/src/Illuminate/Foundation/helpers.php#L641

`function redirect($to = null, $status = 302, $headers = [], $secure = null)` is a helper function offered by Laravel.

`@return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse`

**Comment by judgej** [comment]
I'll just leave this here:

```php
Route::get('redirect', ['uses' => 'TestController@redirect']);

class TestController extends Controller
{
    protected function doIt()
    {
        // Go home!
        return redirect('/');
    }

    public function redirect()
    {
        $this->doIt();

        return 'Why am I still here?';
    }
}
```

**Comment by jrean** [comment]
I finally got your point and understood what you mean!
Thank you for leaving this here ;-)

**Comment by jrean** [comment]
@judgej 
https://github.com/jrean/laravel-user-verification/releases/tag/v2.2.27

Would you be kind to test? It should work for your Laravel version.

Thanks again!

**Comment by judgej** [comment]
Will do in the morning. Thanks for bearing with me :-)

**Comment by judgej** [comment]
It's nearly there, but does not validate at all now.

Your `validateRequest()` returns a `false` if validation fails, or a `null` if validation is successful.

Then `getVerification()` sees both results as a failure, and considers the email to be missing or invalid.

```php
        if (! $this->validateRequest($request)) {
            return redirect($this->redirectIfVerificationFails());
        }
```

This method:

```php
    protected function validateRequest(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email'
        ]);

        if ($validator->fails()) {
            return false;
        }
    }
```

works like this:

```php
    protected function validateRequest(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email'
        ]);

        return $validator->passes();
    }
```
