### ISSUE TITLE
where to apply route

### ISSUE THREAD

**Issue by brazitech** [jrean/laravel-user-verification#120]
being new to laravel..  i am having trouble understanding where to do the following:
Apply the middleware on your routes:

Route::group(['middleware' => ['web', 'isVerified']], function () {
    // …
can someone please explain with a little more detail;
Route::group(['middleware' is not in the route file
also ...i am using homestead and laravel 5.4
thank you
Gator

**Comment by BryanYeh** [comment]
Look over the Laravel Documentation for Route Group Middleware. https://laravel.com/docs/5.4/routing#route-groups

--------

The documentation needs an update. It should be 
```
Route::group(['middleware' =>'isVerified'], function () {
    // …
```

Let's say you have 5 pages for a blog:
1. User profile (needs to be logged in)
2. Create Post (needs to be logged in)
3. Login page (do not need to be logged in)
4. Register Page (do not need to be logged in)
5. View Everyone's Post Page (do not need to be logged in)

As you can see 1 and 2 needs to be logged in. You will want "create" a group with the middleware **isVerified** for cleaner code.
```
Route::group(['middleware' => 'isVerified'], function () {
    Route::get('/user-profile', 'UserController@view'); // this route uses uses 'isVerified' middleware
    Route::get('/create-post', 'PostsController@create'); // this route uses uses 'isVerified' middleware
});
```

If you don't put it into a group your links will look like this:
```
Route::get('/user-profile',  'UserController@view')->middleware('isVerifed'); // this route uses uses 'isVerified' middleware
Route::get('/create-post', 'PostsController@create')->middleware('isVerifed'); // this route uses uses 'isVerified' middleware
```

Overall your web.php route file will look something like this:
```
<?php
Route::get('login', 'Auth\LoginController@login');
Route::get('register', 'Auth\RegisterController@register');
Route::get('/view-posts', 'PostsController@view');

Route::group(['middleware' => 'isVerified'], function () {
    Route::get('/user-profile', 'UserController@view');
    Route::get('/create-post', 'PostsController@create');
});
```

**Comment by jrean** [comment]
Hi @BryanYeh thanks for the help.
Why did you write the package documentation needs to be updated to?

> Route::group(['middleware' =>'isVerified'], function () {

**Comment by BryanYeh** [comment]
@jrean From Laravel version 5.3 and 5.4 API routes and WEB routes are separated. 

If you look at the Laravel directory 5.3 and 5.4 there's a routes folder (same location as app folder) with api.php and web.php. (web middleware isn't needed since the routes will be in the web.php)

But before version 5.3 the routes.php is in the app/Http. (web middleware is needed)

**Comment by brazitech** [comment]
Thank you  for the great help.
got it working and now understand a lot more on how Laravel handles auth.
you need to to do a newbee web page. your answers are a great help,
thanks again 
Gator

**Comment by BryanYeh** [comment]
@brazitech You're welcome glad you understand what I wrote. 
There's Google, Youtube, Laravel Documentation, Laracasts ( I think most of the videos need to be paid for to watch). There are lots of tutorials out there in the wild. 
I don't think a newbee webpage is needed. From what I see creating a simple blog tutorial (Google search and Youtube will have it) is enough to understand the most part of Laravel.

**Comment by jrean** [comment]
@BryanYeh thank you for the note about the documentation ;-)

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.5
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.23
