### ISSUE TITLE
Use toMail toWebhook Notifiable

### ISSUE THREAD

**Issue by aurawindsurfing** [jrean/laravel-user-verification#121]
Would it be possible to add ability to use webhook. This will allow to ise services like mailgun, sendinblue etc instead of handling email templates and also sending emails itself.

**Comment by jrean** [comment]
Hi @aurawindsurfing, do you mean using the "Notification" implementation provided by Laravel?

**Comment by aurawindsurfing** [comment]
Yes. However now that I think about it this is only one or two email user receives so maybe there os no point to write the whole new implementation. Just use what is provided and then move the rest of the notifications to the Laravel Notification. Thanks for your time!
