### ISSUE TITLE
Class user.verification does not exist

### ISSUE THREAD

**Issue by Cheesper** [jrean/laravel-user-verification#125]
Thanks for your work, but I got issue like many others.  I followed the documentation step by step.

Class user.verification does not exist

at ReflectionClass->__construct('user.verification') in Container.php line 719
at Container->build('user.verification') in Container.php line 598
at Container->resolve('user.verification') in Container.php line 567
at Container->make('user.verification') in Application.php line 708
at Application->make('user.verification') in Container.php line 1139
at Container->offsetGet('user.verification') in Facade.php line 159
at Facade::resolveFacadeInstance('user.verification') in Facade.php line 128
at Facade::getFacadeRoot() in Facade.php line 215
at Facade::__callStatic('generate', array(object(User))) in RegisterController.php line 95
at RegisterController->register(object(Request))

Model User
Laravel Version 5.4.18

php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider" --tag="config"
not worked, I copied by hand user-verification.php, it's not important

**Comment by Cheesper** [comment]
Found problem, I'm forgot to add line 
Jrean\UserVerification\UserVerificationServiceProvider::class, 
to /config/app.php in providers sections!

**Comment by nawazm** [comment]
I've put ServiceProviders and Faceds alias in my config/app.php

But still getting this error
`Class user.verification does not exist`

**Comment by jrean** [comment]
Hi,
Can you please give more details:
- Laravel version
- package version
- your controller code sample

Thxs.

**Comment by nawazm** [comment]
Laravel 5.4.18 (recently updated)

this is my RegisterController code
`<?php

namespace Securmate\Http\Controllers\Auth;

use Securmate\Customer;
use Securmate\Devices;
use Securmate\Mailers\AppMailer;
use Securmate\Http\Controllers\Controller;

use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Auth\Events\Registered;

use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;
    use VerifiesUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => ['getVerification', 'getVerificationError']]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        $messages = [
            'first_name.required'   =>  'Your First Name is required.',
            'last_name.required'    =>  'Your Last Name is required.',
            'email.required'        =>  'Your Email address is required.',
            'captcha'          =>  'Invalid captcha.',
        ];

        return Validator::make($data, [
            'first_name' => 'required|max:32',
            'last_name' => 'required|max:32',
            'email' => 'required|email|max:128|unique:customers',
            'password' => 'required|min:10|regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{10,}$/|confirmed',
            'captcha' => 'required|captcha',
            'terms' => 'accepted'
        ], $messages);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        $customer = Customer::create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'ip_address' => $_SERVER['REMOTE_ADDR'],

        ]);
        
        return $customer;
    }

    /**
    * Handle a registration request for the application.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        $customer = $this->create($request->all());

        event(new Registered($customer));

        $this->guard()->login($customer);

        UserVerification::generate($customer);

        UserVerification::send($customer, 'Verify your email');

        return $this->registered($request, $customer)
                        ?: redirect($this->redirectPath());
    }
}
`

**Comment by nawazm** [comment]
Publishing doesn't work for me
![image](https://cloud.githubusercontent.com/assets/1366017/25036616/683614ae-2112-11e7-8d26-60e762be1ef7.png)
