### ISSUE TITLE
Automatic login after clicking on the link with the token

### ISSUE THREAD

**Issue by Simpson1993** [jrean/laravel-user-verification#126]
When I click on the link with the token I want to redirect in my homepage and be already logged. How can I implement this? Thank you)

**Comment by gmask** [comment]
I'm wondering how to do this as well. I figure that I need to add `$this->guard()->login($user);` somewhere but I'm not sure how or where.

**Comment by Simpson1993** [comment]
Solve this problem. Add to my **register** function (RegisterController) event **listener**:

```
 public function register(VerificationRequest $request)
 {
       ...
       event(new Registered($user));
       ...
 }
```

Than create **listener**:

```
<?php

namespace App\Listeners;

use Illuminate\Auth\AuthManager;
use Jrean\UserVerification\Events\UserVerified;

/**
 * Class UserVerifiedListener
 * @package App\Listeners
 */
class UserVerifiedListener
{
    /**
     * @var AuthManager
     */
    private $auth;

    /**
     * Create the event listener.
     *
     * @param AuthManager $auth
     */
    public function __construct(AuthManager $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Handle the event.
     *
     * @param  UserVerified  $event
     * @return void
     */
    public function handle(UserVerified $event)
    {
        $this->auth->guard()->login($event->user);
    }
}
```
And register this in :

> app/Providers/EventServiceProvider.php

```
<?php

namespace App\Providers;

use App\Listeners\UserVerifiedListener;
use Illuminate\Support\Facades\Event;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Jrean\UserVerification\Events\UserVerified;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        UserVerified::class => [
            UserVerifiedListener::class
        ],
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }

    public function register()
    {
        $this->app->bind(UserVerifiedListener::class, function () {
            return new UserVerifiedListener(
                $this->app->make('auth')
            );
        });
    }
}
```

**Comment by jrean** [comment]
@Simpson1993 @gmask 
Thank you for your feedback.

I published a new release:
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.6

Publish or (delete) and re-publish the package config file:
`php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider" --tag="config"`

Then set `'auto-login'` as `true`: `'auto-login' => true,`

Hope it will help you. Don't hesitate to share your feedback :-)

**Comment by gmask** [comment]
Hmm, this change seems to have broken my app's setup:

* I have disabled auto-login on *register* so that the user must verify their email first. Since updating the package auto-login on *register* seems to be re-enabled, changing the config doesn't seem to alter anything.

I'd like the following workflow:

* When a user registers they are sent the verification email, they are *not* automatically logged in.
* When they click on the "Verify Email" link in the email they *are* automatically logged in if the verification succeeds.

**Comment by jrean** [comment]
@gmask as mentioned into the documentation:
> Note that by default the behavior of Laravel is to return an authenticated user after the registration step.

```
/**
        * Handle a registration request for the application.
        *
        * @param  \Illuminate\Http\Request  $request
        * @return \Illuminate\Http\Response
        */
        public function register(Request $request)
        {
            $this->validator($request->all())->validate();

            $user = $this->create($request->all());

            event(new Registered($user));

            $this->guard()->login($user);

            //UserVerification::generate($user);
            //UserVerification::send($user, 'My Custom E-mail Subject');

            return $this->registered($request, $user)
                            ?: redirect($this->redirectPath());
        }
```

So by default, when a user registers, he is logged in. If you want to change this behavior you need to do it while overwriting the `register()` method.

Then later, when the verification process is performed, with the new package update, you can simply decide to log the user in by changing the config file value from `false` to `true`.

**Comment by gmask** [comment]
@jrean Yes I mentioned that I have already overridden the `register()` method, here it is:

```
    public function register(Request $request)
    {
        $alert = ['type' => 'warning', 'title' => 'Verify your email', 'message' => 'Before logging in you must verify your email address: click the link in the email that we just sent you.'];

        $this->validator($request->all())->validate();

        event(new Registered($user = $this->create($request->all())));

        UserVerification::generate($user);
        UserVerification::send($user, 'Verify Your Email Address');

        return $this->registered($request, $user) ?: redirect('/alert')->with('alert', $alert);
    }
```
The issue only appears when I leave the cookies after a `migrate:refresh`.
