### ISSUE TITLE
testing doesn't work with Mail::fake()

### ISSUE THREAD

**Issue by mtmail** [jrean/laravel-user-verification#127]
When following the test pattern in https://laravel.com/docs/5.4/mocking#mail-fake I receive the error
```
Argument 1 passed to Jrean\UserVerification\UserVerification::__construct()
must be an instance of Illuminate\Mail\Mailer,
instance of Illuminate\Support\Testing\Fakes\MailFake given
```

The class `MailFake` implements `Mailer` but of course the type function type declaration fails in https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L46

I changing it to `public function __construct($mailer, Builder $schema)` to get all tests passing. But adding another using http://php.net/manual/en/function.class-implements.php might be better.

**Comment by jrean** [comment]
@mtmail 
This release should fix your issue.
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.7

The constructor now require a `Mailer` contract type `Illuminate\Contracts\Mail\Mailer;`

Please test and share your feedback.

**Comment by mtmail** [comment]
@jrean Works great! Thank you very much.
