### ISSUE TITLE
Can't access the email verification error page

### ISSUE THREAD

**Issue by chizzycrusty** [jrean/laravel-user-verification#128]
I followed all of the step by step carefully, the email is sent and link works. However, if my user is not verified, I can't access the error page as I always get redirect to my home page with this error:

> UserNotVerifiedException in IsVerified.php line 26:
This user is not verified.

So how can I access the error page ?

**Comment by jrean** [comment]
Hi @chizzycrusty 
Thank you for the feedback.

The behavior you experience is how the package works.

You are using the provided middleware:
https://github.com/jrean/laravel-user-verification/blob/master/src/Middleware/IsVerified.php

The handle method is checking if the user is verified or not.

If the user is not verified an exception is thrown.

```
        if(! is_null($request->user()) && ! $request->user()->verified) {
            throw new UserNotVerifiedException;
        }
```

So you are free to implement your own logic to manage the following exception.
For instance you can use the Laravel Exception handler :-)

Cheers,

**Comment by the94air** [comment]
@chizzycrusty Handler Example
```
<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Auth\AuthenticationException;
use Jrean\UserVerification\Exceptions\UserNotVerifiedException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that should not be reported.
     *
     * @var array
     */
    protected $dontReport = [
        \Illuminate\Auth\AuthenticationException::class,
        \Illuminate\Auth\Access\AuthorizationException::class,
        \Symfony\Component\HttpKernel\Exception\HttpException::class,
        \Illuminate\Database\Eloquent\ModelNotFoundException::class,
        \Illuminate\Session\TokenMismatchException::class,
        \Illuminate\Validation\ValidationException::class,
    ];

    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        if ($exception instanceof UserNotVerifiedException) {
            return response()->view('auth.errors.not-verified', [], 401); //  <----- The magic
        }

        return parent::render($request, $exception);
    }

    /**
     * Convert an authentication exception into an unauthenticated response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $exception
     * @return \Illuminate\Http\Response
     */
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }

        return redirect()->guest(route('signin'));
    }
}
```

**Comment by famelis** [comment]
Thank you @the94air for pointing out the code but this needs another view and leaves the non verified user logged in.

I used the following method to have the job done

a) I copied from `.../views/auth/register.blade.php` the lines at start, to the login view

```php
@if(Session::has('alert'))
<div class="alert alert-success">
    {{ Session::get('alert') }}
    @php
    Session::forget('alert');
    @endphp
</div>
@endif`
```
 to the `.../views/auth/login.blade.php` view

b) changed the render function to 
```php
public function render($request, Exception $exception) {
    if ($exception instanceof UserNotVerifiedException) {
        $request->session()->flush();
        $request->session()->put('alert', 'You have to verify your email!');
        return redirect('/login');
    }
    return parent::render($request, $exception);
}
```
and the user is redirected to the login page with an alert showing why he is not allowed to login.

**Comment by the94air** [comment]
Hey @famelis. your solution will perfectly work and in my situation, I was using `isVerified` with the `auth` middleware, that's why all requests are redirected to that page. All users will not have access to all pages unless they verify (without logging them out) and they can logout as they want. Of course you will leave the logout without the `isVerified` middleware. Hope that I am clear now :smile:

**Comment by randercarlos** [comment]
Hey @jrean 

Thanks for the package. 

An error is occurring and I do not know how to solve.

I have a login screen with an email field and password plus a remember me checkbox.

If a user registers through the registration screen, and without checking the email, try to log in using the registered email and password and with the remember me checkbox checked.

The system goes into infinite loop (ERR_TOO_MANY_REDIRECTS)

The problem is in error handling:

`App\Exceptions\Handler.php`

` public function render($request, Exception $exception)
    {
        $request->session()->flush();
        
        
        if ($exception instanceof UserNotVerifiedException) {
            return redirect('/login')->with('warning', 'Esse usuário ainda não foi verificado!');
        } else if ($exception instanceof UserIsVerifiedException) {
            return redirect('/login')->with('warning', 'Esse usuário já foi verificado!');
        } else if ($exception instanceof UserNotFoundException) {
            return redirect('/login')->with('warning', 'Usuário não encontrado!');
        } else if ($exception instanceof TokenMismatchException) {
            return redirect('/login')->with('warning', 'Token de verificação inválido!');
        }

        return parent::render($request, $exception);
    }`

How to solve this?

Thanks and sorry for bad English...
