### ISSUE TITLE
Custom email view

### ISSUE THREAD

**Issue by chil360** [jrean/laravel-user-verification#129]
After the changes for Markdown email support, you can no longer set a custom view for the email as it is now hardcoded in the VerificationTokenGenerated class.

Can you add this feature again, please?

**Comment by jrean** [comment]
Hi,
Can you please share more details because both options should be supported :-)

**Comment by chil360** [comment]
Used to be able to set the email view using UserVerification::emailView() but this was removed in the markdowm commit (https://github.com/jrean/laravel-user-verification/commit/d9d3fc51da19da1ab42d1b73d731d25e89fabc00)

The email view name is now hardcoded here:
https://github.com/jrean/laravel-user-verification/blob/master/src/Mail/VerificationTokenGenerated.php#L79
Similarly, the markdown view is also hardcoded:
https://github.com/jrean/laravel-user-verification/blob/master/src/Mail/VerificationTokenGenerated.php#L77

**Comment by jrean** [comment]
Ok got it.
But, you can both publish and customize the view and the Markdown view. It's not enough?

I'll work on it.

**Comment by chil360** [comment]
It's not a big issue, just trying to group my views together in a more modular way.

Thanks for looking at this.

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.8
Can you please test? It should be good now :-)

**Comment by chil360** [comment]
Tested & working. Thanks!
