### ISSUE TITLE
Include Plain Text Emails

### ISSUE THREAD

**Issue by Jaspur** [jrean/laravel-user-verification#134]
Hi, 
Message only has text/html MIME parts what is a -1 score for the SpamAssassin filter. This is the reason my emails get marked as spam. 
Can you add a text-variant also?

**Comment by jrean** [comment]
@jaspur can you please give me more details?
I'm not sure to understand your point.

Thank you

**Comment by Jaspur** [comment]
If you run the e-mail via mail-tester.com, you can see it highly recommends you to use a text-variant of the email also, a non HTML-version.

**Comment by jrean** [comment]
Got it! Thanks. I will draft something and implement a fix asap.

**Comment by lipiniak** [comment]
Hi any news on this? Im realy looking forward to implement this.

**Comment by toothbrush7777777** [comment]
@jrean Any update? Is this already implemented?

**Comment by mailnike** [comment]
Hi, just checking. Is this already done? How do I enable it? If not done, then any work around?
