### ISSUE TITLE
Can't change $subject "My Custom E-mail Subject"

### ISSUE THREAD

**Issue by jorenvh1** [jrean/laravel-user-verification#136]
Hey, can someone explain how to properly set the emails subject?

It appears as "My Custom E-mail Subject" for me now....

**Comment by the94air** [comment]
I think you need to add a global to your .env file
```env
MAIL_FROM_NAME="My Custom E-mail Subject"
```

**Comment by jrean** [comment]
Hi,
I will reply with more details later but you simply need to set the second parameter of the send($user, "Email title", ...

Please refer to the documentation.

Cheers

J.

**Comment by jorenvh1** [comment]
Alright but I haven't changed anything to the code, so I haven't overwritten anything, where is this function feing called?

**Comment by jrean** [comment]
@jorenvh1 please read the documentation.

To use the package you updated the following `app\Http\Controllers\Auth\RegisterController.php` with:

```
/**
        * Handle a registration request for the application.
        *
        * @param  \Illuminate\Http\Request  $request
        * @return \Illuminate\Http\Response
        */
        public function register(Request $request)
        {
            $this->validator($request->all())->validate();

            $user = $this->create($request->all());

            event(new Registered($user));

            $this->guard()->login($user);

            UserVerification::generate($user);

            UserVerification::send($user, 'My Custom E-mail Subject');

            return $this->registered($request, $user)
                            ?: redirect($this->redirectPath());
        }
```

As you can see `UserVerification::send($user, 'My Custom E-mail Subject');` the `send()` method is called and the second parameter is the e-mail subject.

In the documentation (and the code source) you can see the method signature:
`send(AuthenticatableContract $user, $subject = null, $from = null, $name = null)`

Cheers

**Comment by jorenvh1** [comment]
My bad... totally forgot that method was called there...
