### ISSUE TITLE
Use Notifications instead of Mail 

### ISSUE THREAD

**Issue by the94air** [jrean/laravel-user-verification#137]
it is better to use laravel notification because you should make a view for both the verify and the send again feature. also you may need to send an SMS for verifying instead of email.

**Comment by the94air** [comment]
I also notice that the verify token is not encrypted and stored directly to the database . the token seem to be long but i think it should be also at least encrypted

**Comment by jrean** [comment]
Hi,
Regarding your first comment, I keep it in mind for the next version. Currently, the package is made to verify an e-mail which is different from verifying a telephone number with an SMS.

About the second comment; this package follows what Laravel (internally) does.

Thxs

**Comment by ivansammartino** [comment]
I'd like this too, to match the standard ResetPasswordNotification class used for resetting passwords in scaffolded auth (\Illuminate\Auth\Passwords\CanResetPassword.php)... Pleeeease :-)
