### ISSUE TITLE
How and which function should override to make token of 4 character 

### ISSUE THREAD

**Issue by niklesh-etruesign** [jrean/laravel-user-verification#143]
I am trying to make token of 4 character.  I made one queue to send email where I need to send token of 4 character. I checked some vendor classes but didn't find the way. Please suggest me to get this done.

**Comment by jrean** [comment]
Hi,

In the `UserVerification.php` file
You need to rewrite the `protected` method `generateToken()` and implement your logic if this is what you want to achieve.

Cheers

**Comment by niklesh-etruesign** [comment]
I am trying to override function in `RegisterController` , I am unable to override function `generateToken()` here because `generate()` is calling this function. And I am calling `generate()` like `UserVerification::` from `RegisterController`.

Also I request you to guide me on Reset Password functionality where I need also change token to 4 character.

Thanks for your time.

**Comment by jrean** [comment]
I close this as it is not a package related issue.
