### ISSUE TITLE
ModelNotCompliantException

### ISSUE THREAD

**Issue by simioluwatomi** [jrean/laravel-user-verification#145]
I am getting this error. Even though I know it is in the docs that Models should implement the authenticatable interface which I have done. I tried the following but no success

1.  `use Illuminate\Foundation\Auth\User as Authenticatable;`
This produces a ModelNotCompliantException.
2. `use Illuminate\Contracts\Auth\Authenticatable`.
This produces a fatal error. `App\model_name cannot extend from interface lluminate\Contracts\Auth\Authenticatable`.
3.
```
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;
use Eloquent;
class Model extends Eloquent  implements Authenticatable
{
use AuthenticableTrait;
```
This also produces a ModelNotCompliantException

My use case is Multi Auth and I am trying to confirm e-mail addresses of the second type of user. Any help would be appreciated. Thank you.

**Comment by jrean** [comment]
Hi,

The exception you receive is thrown because your table `users`? is missing one or two mandatory columns needed by this package (`verified` and `verification_token`).

Refer to the documentation for running the migration script.

Cheers

**Comment by simioluwatomi** [comment]
Yes... I discovered that hours of debugging. Was too tired to come back here to do a reply. Why not update the doc to say `ModeNotCompliant exception is a result of ...` So that people would know where to look immediately they have that problem?

Also, is there a tutorial anywhere that shows how to use this package with all its bells and whistles?

**Comment by jrean** [comment]
I will update the documentation to make it more detailed. Thank you for your feedback.
