### ISSUE TITLE
it's be also nice to implement a login only for verified account

### ISSUE THREAD

**Issue by lfarkas** [jrean/laravel-user-verification#15]
which is not so simple, since have to create a new guard based on SessionGuard and overwrite hasValidCredentials.

**Comment by jrean** [comment]
@lfarkas thank you.
Can you please be more specific has I'm not sure to understand what you mean.
Cheers

**Comment by lfarkas** [comment]
currently only a verified field set to true during email verification. after this it's not used for anything and there is not any kind of instruction how can be used. of course everybody can use this field in the app's policy class or even manually but for example a small example where 'auth' middleware also implied that the user also verified would be useful. or write a "verified" middleware which can be used similary to auth middleware even in the route configuration.

**Comment by jrean** [comment]
Agree.
In past releases the package was tied to an authenticated user. It has been requested to remove this behaviour to allow more flexibility. So now we can use the package without needing an authenticated user. But of course you can implement such behaviour. Again this package only exists to solve one thing ; the user e-mail verification. The way people implement and use the feature is out of the scope.
I will write a tutorial and give some detailed examples.
Thank you!

**Comment by lfarkas** [comment]
this is another good implementation:
https://github.com/tjbp/laravel-verify-emails
it's console helper also would be a good enhancement.

this can be a good implementation for the middleware i'm talking about and i'd call it auth.verified similar to auth.basic
https://github.com/tjbp/laravel-verify-emails/blob/master/src/Auth/Middleware/AuthenticateAndVerifyEmail.php

this feature which makes the verified attribute renameable to anything else also can be a good feature:
https://github.com/tjbp/laravel-verify-emails/blob/master/src/Auth/VerifyEmails/CanVerifyEmail.php

this is an example to always (re)send verification:
http://hapnic.com/2015/05/10/email-based-user-activation-in-laravel-5-the-right-way/
may be not a good idea to always send, but in the current implementation if the first email not arrive or lost in the spam folder or.....then there is no automatic way to resend verification email.
and may be a given verification token should expire eg aftera a few days. in this case regeneration and resend would be useful. here is something similar:
http://blog.damirmiladinov.com/laravel/laravel-5.2-email-verification-with-activation-code.html

and last but not least here is the best description and solution:
http://www.krucas.com/2016/04/user-email-verification-for-laravel-5/

**Comment by jrean** [comment]
Thank you for all the links! I will read and see what to extract / improve.

Regenerating and resending are already implemented. Simply use (reuse) the "generate()" method and it will do again the entire process. Have a look at the method.


Jean

**Comment by lfarkas** [comment]
possible to regenerate bit no web interface no simple resend button etc...
