### ISSUE TITLE
files and folders aren't sync after installation

### ISSUE THREAD

**Issue by ATNoosh** [jrean/laravel-user-verification#151]
Hi.
After I installed the package successfully on laravel5.2, some of the files in the git aren't in my repo.
For example migrations aren't in my repo.
I run php artisan migrate --path="/vendor/jrean/laravel-user-verification/src/resources/migrations"
but says nothing to migrate!

**Comment by jrean** [comment]
Hi @ATNoosh 
For Laravel 5.2 use the 2.2 branch (https://github.com/jrean/laravel-user-verification/tree/2.2)
Following the documentation, for the 2.2 branch migrations are not included, you have to do it manually.
