### ISSUE TITLE
Where to apply the Attributes/Properties to override.

### ISSUE THREAD

**Issue by hiddenicon** [jrean/laravel-user-verification#153]
Where would you configure or apply the 6 custom attributes/properties to override some of the settings? I've tried in some of the config files, and the user.php class, in the registercontroller.php class, etc. It doesn't appear to be picked up when I attempt to configure these attributes.

**Comment by nkeena** [comment]
You would apply them to whichever class is implementing the `VerifiesUser` trait.

For example, if you are using it in your `RegisterController` class you could do something like this:

```php
class RegisterController extends Controller
{
    use RegistersUsers, VerifiesUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/account';
    protected $redirectAfterVerification = '/account';

...
```

**Comment by hiddenicon** [comment]
Ok that worked. I started with that one, but I was trying the
`$redirectIfVerificationFails = '/email-verification/error';`
Attribute. This one still doesn't appear to be working. Other attributes are working fine when defined in RegisterController.php. 

When I have a verification error I am seeing the Laravel Whoops error (laravel 5.5) instead of it redirecting to /email-verification/error.

**Comment by hiddenicon** [comment]
yes confirmed again that all attributes/variables work when adding them to the RegisterController.php file. I'm still not able to get the error view to load, I'm still getting the default Laravel Whoops error pages.

**Comment by jrean** [comment]
@hiddenicon 
>By default this packages ships with two routes.

```
Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')->name('email-verification.check');
```

So you should be able to hit the route `http(s)://domain.com/email-verification/error` which will display the default package error view.

By default the package property `$redirectIfVerificationFails = '/email-verification/error';`
If you override it with a new end-point (route) then you should define this new route into your route file.

Let me know,

Cheers

**Comment by hiddenicon** [comment]
I have the default routes from your package installed. I see them listed. I didn't override the `$redirectIfVerificationFails` just yet, that is still default. However, if I fail a verification I get the default Laravel Whoops error page instead of the one in your package. 

My routes:
![image](https://user-images.githubusercontent.com/10273594/33303747-fa7c42fc-d3d2-11e7-8489-e30b8c53774a.png)

Would ever error for verification redirect to your page? Or only certain errors?

**Comment by jrean** [comment]
Hi @hiddenicon,
Can you please show us the trace of the error "Whoops"? (logs)

The behaviour of the package is simple, if the verification fails, it will redirect the user to the "email-verification/error" (route/page).

When you see the "Whoops" page, what is the URL you see in the browser?

I'm wondering if you don't have an error somewhere else, related or not related to the package.

**Comment by hiddenicon** [comment]
One example is attempting to log in and the user hasn't verified the account yet:

![image](https://user-images.githubusercontent.com/10273594/33351674-ef44efa6-d472-11e7-9d28-249c5fbbc118.png)

**Comment by jrean** [comment]
@hiddenicon I think you miss-understand the package behaviour.
What you show is normal.

Any route you put under the `IsVerified` middleware will have to pass the middleware test. If the test fails then a `UserNotVerifiedException` is thrown. It is your duty/work to handle this exception (with the Laravel exception handler for instance).

> This package provides an optional middleware throwing a UserNotVerifiedException. Please refer to the Laravel Documentation to learn more about how to work with the exception handler.

Doing so you will be able to achieve what you want; maybe sending the user to a new route with a dedicated message.

The `Route::get('email-verification/error',...` is not for that Exception, it is used during the verification process when you verify the user e-mail and the token. If something goes wrong at that time then the user will be redirected to the default route provided by the package or by any new custom route/end-point you may provide by adding a custom attribute.

```
/**
     * Get the redirect path for a failing token verification.
     *
     * @return string
     */
    public function redirectIfVerificationFails()
    {
        return property_exists($this, 'redirectIfVerificationFails') ? $this->redirectIfVerificationFails : route('email-verification.error');
    }
```

Hope it helps you.

Let me know.

**Comment by hiddenicon** [comment]
I see now. You are correct, I misunderstood. I thought all of the pieces including your middleware was doing any exception redirecting to the error view. 

I will work on the try/catch and config in the middleware to accomplish what I'd like. 
Thanks for the info and thanks for this package, saved me a lot of time of doing it all myself.
