### ISSUE TITLE
Encryption (Question)

### ISSUE THREAD

**Issue by maximaexchen** [jrean/laravel-user-verification#155]
Hi.
For a project I need to have all user mails to be saved encrypted to the database.
As I see, I only give the whole user object to the UserVerification process, right?
Is there a way to encrypt the email before sending the mails, or do I have to override all methods by extending the UserVerification class?
Any tip appreciated.

**Comment by jrean** [comment]
Hi @maximaexchen 
What about applying an accessor to your User model?
https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor

Then, if you try to access the `$user->email` it could return the "decrypted" e-mail.

Let me know.

Cheers

**Comment by maximaexchen** [comment]
Oh man. I didn't think about that. Still learning a lot.
Works like a charm!
Thanks a lot. You made my day!

**Comment by jrean** [comment]
You're welcome.
I close the issue.

Feel free to comment or open a new one if you need more help.

Learning never ends :-)
