### ISSUE TITLE
Route override not getting replaced

### ISSUE THREAD

**Issue by duongtdvn** [jrean/laravel-user-verification#157]
I'm currently implementing route override with multi-auth system on laravel 5.5 which separate user protected route will go to their domain as the following:

`Customer` user route to
```
customer.domain.dev
```
and `Employee` user route to
```
employee.domain.dev
```
And I have moved all the authenticate route to under difference user and of course the email verifications route should be moved too. The problem here is the route override for the user domain is not getting replaced, the fact is it still looking for verification methods in the default once `App\Http\Controllers\Auth\RegisterController`. I also added the `UserVerificationServiceProvider` before application `RouteProvider` but getting no luck. So, currently i have solved the problem by implement difference routes for the verification and yes It work perfectly by now.

But for the default verification routes it is still there, and people still may access these routes unless it is getting replaced. So, my though about this is instead of loading the default route in the Provider should we map it with RouteProvider?

**Comment by jrean** [comment]
Hi @duongtdvn 

If you want to override/replace default package routes:
https://github.com/jrean/laravel-user-verification#overriding-package-routes


To define your own custom routes, put the package service provider call before the RouteServiceProvider call in the app/config.php file.

```
   /*
    * Package Service Providers...
    */
    Jrean\UserVerification\UserVerificationServiceProvider::class,

   /*
    * Application Service Providers...
    */
    // ...
    App\Providers\RouteServiceProvider::class,
```

Then, add your custom routes to your route file.

**Comment by duongtdvn** [comment]
Hi @jrean 

I have followed as the document which as same as your comment but it did not work as expected. Also note that it work with naked domain but route domain is not. I am working on fresh install of laravel 5.5 without it seem not caused by third party package. Also note that I have ran
```console
php artisan route:clear
php artisan cache:clear
```
still not getting any luck.

**Comment by simioluwatomi** [comment]
This is happening to me too. I have two types of users so I setup multi-auth. But one kind of user would be using the web and another would be using an app. The web user has the full auth package but since the name of the model is not `User`, I decided to refactor my controllers according to the project needs.

After refactoring, I deleted `Auth::routes()` in my route file and ran `php artisan route:list` which continued to fail because 'App\Http\Controllers\Auth\RegsiterController` could not be found. So I copied a `RegisterController` into that namespace and decided to look for the route that needed the Controller in the first place. To my surprise, your package is calling on the Controller.

I'll paste all required files so that you understand my surprise.

```
Route::group(['namespace' => 'Web\Auth'], function()
{
    //Registration routes
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('ministry.register.form');
    Route::post('/register', 'RegisterController@register')->name('ministry.register');
    Route::get('/verify/error', 'RegisterController@getVerificationError')->name('email-verification.error');
    Route::get('/verify/{token}', 'RegisterController@getVerification')->name('email-verification.check');
});
```

```
        /*
         * Package Service Providers...
         */
        Jrean\UserVerification\UserVerificationServiceProvider::class,       

        /*
         * Application Service Providers...
         */        
        App\Providers\RouteServiceProvider::class,
```

Route:list as generated by Laravel
```



GET\|HEAD | email-verification/check/{token} | email-verification.check | App\Http\Controllers\Auth\RegisterController@getVerification |  
  | GET\|HEAD | email-verification/error | email-verification.error | App\Http\Controllers\Auth\RegisterController@getVerificationError


```
