### ISSUE TITLE
Info after email verification

### ISSUE THREAD

**Issue by lipiniak** [jrean/laravel-user-verification#158]
Hi 

How can i create a message of succes verification after user clicked verification link in email?
And i need to change route after verification

**Comment by jrean** [comment]
Hi,

The logic behind the verification is found at `https://github.com/jrean/laravel-user-verification/blob/master/src/Traits/VerifiesUsers.php`. As you can read the `public function getVerification(Request $request, $token)` is returning `return redirect($this->redirectAfterVerification());` if everything is all good...

The logic behind the redirect is found at `https://github.com/jrean/laravel-user-verification/blob/master/src/Traits/RedirectsUsers.php`

```
/**
     * Get the redirect path for a successful verification token verification.
     *
     * @return string
     */
    public function redirectAfterVerification()
    {
        return property_exists($this, 'redirectAfterVerification') ? $this->redirectAfterVerification : '/';
    }
```

You can declare a property `redirectAfterVerification` with the path where to redirect and so display a custom message or whatever you will have in mind..

Hope that helps.

**Comment by ivansammartino** [comment]
@jrean that's fine, but I suggest an improvement for future versions:

1. create a new method:
```
// in VerifiesUsers.php
public function afterVerification(){
  return redirect($this->redirectAfterVerification());
}
```
2. replace the return in the `getVerification()` method:
```
...
return $this->afterVerification();
```
In this way, we can override the `afterVerification()` method in `RegisterController.php`, like this:
```
// in RegisterController.php
public function afterVerification(){
  return redirect($this->redirectAfterVerification())->('success', 'User verified, you can now login!');
}
```
Pleeeeease :-)

**Comment by famelis** [comment]
@ivansammartino You can place the `redirectAfterVerification()` method in __app/Http/Controllers/Auth/RegisterController.php__ as follows

````php
public function redirectAfterVerification()
{
    \Session::put('successful-verification', 'Successful verification. Login to enter.');
    return '/login';
}
````
and put an alert in __resources/views/auth/login.blade.php__
````blade
@section('content')
@if(Session::has('successful-verification'))
    <div class="col-md-6 col-md-offset-3 alert alert-success">
        <strong>@lang(Session::get('successful-verification'))</strong>
        @php (Session::forget('successful-verification'))
    </div>
@endif
. . .
````
This supposes that you have `'auto-login' => false,` in __config/user-verification.php__

Of course you would only have to put the alert in the login if @jrean changed the method in __Traits/RedirectsUsers.php__ to this
````php
/**
  * Get the redirect path for a successful verification token verification.
  *
  * @return string
  */
public function redirectAfterVerification()
{
    if (property_exists($this, 'redirectAfterVerification')) {
        return $this->redirectAfterVerification;
    } else {
        \Session::put('successful-verification', 'Successful verification. Login to enter.');
        return '/login';
    }
}
````
