### ISSUE TITLE
What about displaying errors?

### ISSUE THREAD

**Issue by miranrasuli** [jrean/laravel-user-verification#16]
In your example you mentioned some exceptions, but how should we display them in somewhere like `errors/user-verification.blade.php` view?

I've used $message and:

```PHP
@if (count($errors) > 0)
	@foreach ($errors->all() as $error)
	    <li>{{ $error }}</li>
	@endforeach
@endif
```

but they doesn't displayed any error.

It would be awesome if you add a simple example for errors View.
Thanks!

**Comment by jrean** [comment]
@miranrasuli `Exceptions` need to be `caught` with a `try catch` statement or handled by the Laravel built in way of handling Exceptions.

`$redirectIfVerificationFails = '/verification/error'` is the customizable route where the user will be redirected if any error occur.

`$verifiationErrorView = 'errors.user-verification';` is the customizable view name that will be loaded and you need to create.

`getVerificationError()` method is called by the `$redirectIfVerificationFails = '/verification/error' endpoint. You are totaly free to override / overwrite this method and implement any logic you want.

```
@if (count($errors) > 0)
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
@endif
```

This won't produce anything as this package is not dealing with any form...

**Comment by miranrasuli** [comment]
@jrean Thank you!
Actually today i reviewed almost all of your code.
So we have an endpoint `getVerification()` that will catch 3 exceptions, so 2 of them will be redirected to `/verification/error`. OK!

but in the `getVerificationError()` method, actually i don't know how to get the message of each exception that will be thrown. Or in `errors/user-verification` view.
I don't know how to get the message.
Maybe i am in a wrong way?

**Comment by miranrasuli** [comment]
@jrean That's cool!!!

**Comment by jrean** [comment]
@miranrasuli your question is really interesting and make me think about a couple of things I will update later.

Into the trait `trait VerifiesUsers` file:

```PHP
/**
     * Handle the user verification.
     *
     * @param  string  $token
     * @return Response
     */
    public function getVerification(Request $request, $token)
    {
        $this->validateRequest($request);
        try {
            UserVerification::process($request->input('email'), $token, $this->userTable());
        } catch (UserNotFoundException $e) {
            return redirect($this->redirectIfVerificationFails());
        } catch (UserIsVerifiedException $e) {
            return redirect($this->redirectIfVerified());
        } catch (TokenMismatchException $e) {
            return redirect($this->redirectIfVerificationFails());
        }
        return redirect($this->redirectAfterVerification());
    }
```

This is the method called when you click on the sent e-mail link (containing the verification token).

It tries to process and may throw the exceptions:

 `UserNotFoundException`. No user found! I reckon this is not the kind of details you want to give to your visitor. So by default, it redirects to the error view and you are free to implement whatever you want! No message is given so into the view you don't know anything about the error...

`UserIsVerifiedException`. The user is already verified. No errors. It just redirects wherever you want. You can override the redirection path into the `trait`.

`TokenMismatchException`. Mmmm. Something weird happened and maybe someone is messing around.  reckon this is not the kind of details you want to give to your visitor. So by default, it redirects to the error view and you are free to implement whatever you want! No message is given so into the view you don't know anything about the error...

I thought the view error is just her to display something went wrong and allow one to simply regenerate the process. Trick, call again `generate()` and it will start the process from scratch on the given user.

So, if you want you can simply overwrite `getVerification()`. It's public.

Reading your journey, I guess I should give access to the errors values into the view and make it customizable. I will draft and implement it.

Hope that helped you

**Comment by miranrasuli** [comment]
@jrean I thought it's not a right question according to the package's README.md and the first answer you gave me. So i removed that because didn't knew whether you will answer me or not. apologies!  
After one year, it is my first project dealing with exceptions on Laravel. 
So finally i got exactly what to do after reading Laravel [Errors](https://laravel.com/docs/5.2/errors) and your Awesome Answer!!!

Thanks +1

**Comment by jrean** [comment]
Awesome :-)
Thanks.
Good luck
