### ISSUE TITLE
Problem with resend the verification token

### ISSUE THREAD

**Issue by rtfmfm** [jrean/laravel-user-verification#164]
Hi!
I'm handling UserNotVerifiedException with the following code:
```
if ($exception instanceof UserNotVerifiedException) {
    auth()->logout();
    return response()->view('auth.errors.notverified', [], 401);
}
```

I'm using auth()->logout(); to logout the user before showing the view because I want to hide the menus which are visible for logged in users. 

In ``notverified.blade.php`` I have a resend button to resend the verification code. For this purpose I have ``resendVerify`` route. What the route do is:
```
public function resendVerify()
{
    UserVerification::generate($user);
    UserVerification::send($user,config('app.name').' :: '.trans('msg.account_verification'));
    return $this->registered($request, $user)
                    ?: redirect('verifypending');
}
```
When I click on Resend button I'm getting error ``Undefined variable: user``.

Can you tell me how to set this variable when the user is not logged in or what is the right approach in this scenario?

Thank you!

**Comment by the94air** [comment]
Leave the user loggedin in the exception `UserNotVerifiedException` and then make middleware for checking if the user is verified this way any not verified user will get a `notverified.blade.php` as a response and you can access the user data from the session `$user = Auth::user();`

**Comment by rtfmfm** [comment]
@the94air, I do not want to leave the user logged in because if it is, it will see menus which are visible only for logged in users... or maybe I can use a Gate like this:
```
Gate::define('verified', function ($user) { 
    if ($user->verified == 1) { 
        return true;
    } 
});
```
And than in ``app.blade.php`` i can close the menu in:
```
@if (Gate::allows('verified'))
     ...
@endif
```

Is this a good approach?

Thank you!

**Comment by rtfmfm** [comment]
When I tried the above (to remove ``auth()->logout();`` from ``UserNotVerifiedException`` I've got this in laravel.log
```
[2018-02-01 14:27:52] local.ERROR: This user is not verified. {"userId":105,"email":"username@gmail.com","exception":"[object] (Jrean\\UserVerification\\Exceptions\\UserNotVerifiedException(code: 0): This user is not verified. at /var/www/html/vendor/jrean/laravel-user-verification/src/Middleware/IsVerified.php:26)
```

Where I'm wrong?

**Comment by the94air** [comment]
Yeah, you are right. That what Gates made for. I can't debug that issue right now. Try to make your own middleware without that exception and that should do it. Keep in mind that there are a lot of ways to do that. Have fun :)

**Comment by rtfmfm** [comment]
@the94air , thank you for your help. I've crated my Middlewhere isVerified and register it. Tried to register it under web and/or routeMiddleware arrays and I'm getting different errors. Can you, please, point me on an example what to include in the middlewhere?

Thank you!

**Comment by rtfmfm** [comment]
In my custom isVerified middleware I have 
```
public function handle($request, Closure $next)
{
    if(! is_null($request->user()) && ! $request->user()->verified) {
        return response()->view('auth.errors.notverified', [], 401);
    }
    return $next($request);
}
```
In the view ``notverified`` I have a link with ``href="{{ route('resendVerify') }}``. The route ``resendVerify`` is outside ``Route::group(['middleware' => ['isVerified']], function () { ... });`` in ``web.php`` and it does: 
```
public function resendVerify()
{
    UserVerification::generate($user);
    UserVerification::send($user,config('app.name').' :: '.trans('msg.account_verification'));
    return $this->registered($request, $user)
                    ?: redirect('home');
}
```
But I think I do not reach this function when I press the link mentioned above. I'm sure my  middleware is wrong, but I do not know where is the mistake. No errors shown in the log or elsewhere.

Would you, please, help me?

**Comment by the94air** [comment]
Sorry @rtfmfm, I don't have a PC right now to debug this issue (This may take a bit longer) so.. I recommend this (package)[https://github.com/meness/verifi] for you it called `verifi`. I think it is easier to use and it is the package that I would use in a situations like this. Try it out and let me know. Thanks.

**Comment by rtfmfm** [comment]
Thank you, @the94air , but ``verifi`` is worst documented and maintained package aroud... 
I hope @jrean will be able to help me, or maybe you when you are back to your PC.

**Comment by rtfmfm** [comment]
The problem is solved. I found two mistakes in my code.
1. My ``resendVerify`` route was poining to RegisterController. Moved the function to another controller.
2. In web.php ``auth`` group was inside ``isVerified`` group. Now It's: 
```
Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => ['isVerified']], function () {
        ...
    });
    Route::get('resendVerify'...));
    Route::get('verifypending'...));
});
``` 
And everything is working.
Thank you for your help, @the94air!

You can close the issue.
