### ISSUE TITLE
Only verifying logged out users?

### ISSUE THREAD

**Issue by amazingdetective** [jrean/laravel-user-verification#173]
User doesn't seem to verify if the user is logged in, only if the user is logged out does the link actually verify the user. Which seems strange as you need to be logged in/check the user to resend confirmation email.

Am I missing something?

**Comment by amazingdetective** [comment]
Nevermind, I'm silly. 

$this->middleware('guest', ['except' => ['getVerification', 'getVerificationError']]); 

In construct

**Comment by ahmednagix** [comment]
and where is that constructor ?
