### ISSUE TITLE
Verification by Token not by Email

### ISSUE THREAD

**Issue by elephantux** [jrean/laravel-user-verification#174]
Now verification do by email only. But if email is not unique field and we got to account with same email second email verification will fails.

Why not get user (from url data) by token?

**Comment by jrean** [comment]
Hi.
Sorry but I am not going to handle such configuration.
If you have "n" accounts with the same e-mail address then if the e-mail has been verified once, the verification is valid for the other accounts sharing the same e-mail...

The best option for you is probably to fork and adapt to your needs.
