### ISSUE TITLE
Allow login when user is not verified

### ISSUE THREAD

**Issue by titleistfour** [jrean/laravel-user-verification#18]
Hello,

I installed this package, and it works well, with the exception of one thing.  A newly registered user who has not verified their account yet (verified = 0) is allowed login access.  Is this behavior intended?

Thanks,
Jay

**Comment by jrean** [comment]
Hi,

Yes!
This package is only responsible for the user verification. If you want to achieve what you are mentioning, simply create a middleware :-)

J

**Comment by titleistfour** [comment]
Thanks for the response.  Not a problem, I'll take care of the middleware.  Thanks for the nice package!

**Comment by clarkewing** [comment]
Hi @titleistfour,

I'm trying to implement the same thing you were trying to do. However, being fairly new to Laravel, I don't really see how to go about creating the middleware for this.
Would you mind telling me how you proceeded?

Thanks,
Hugo
