### ISSUE TITLE
How to redirect user to login page after successful Verification 

### ISSUE THREAD

**Issue by aniket-s** [jrean/laravel-user-verification#180]
How can i redirect user to login page after successful Verification with a custom message saying 'Your account has been verified, Please Login'

Where to edit this line $redirectAfterVerification = '/'; ?

**Comment by jrean** [comment]
Hi @aniket-s 
You can implement the available attributes into the `RegisterController` file.

You can customise:
- `$redirectIfVerified = '/';`
- `$redirectAfterVerification = '/';`
- `$redirectIfVerificationFails = '/email-verification/error';`

**Comment by aniket-s** [comment]
and how to show custom message after successful verification?
