### ISSUE TITLE
Laravel 5.6 support version

### ISSUE THREAD

**Issue by Asxer** [jrean/laravel-user-verification#181]
Now I should set "minimum-stability": "dev" to use laravel-user-verification. I'm not sure if project minimum stability downgrade is a good solution to install your plugin to Laravel 5.6.
Could you please create stable version of plugin?

**Comment by jrean** [comment]
Hi @Asxer 
https://github.com/jrean/laravel-user-verification/tree/6.0

**Comment by Asxer** [comment]
@jrean Thank you very much for fast reply and solution!=)
