### ISSUE TITLE
Revisions not created

### ISSUE THREAD

**Issue by robbielove** [jrean/laravel-user-verification#184]
I use Venturecraft/revisionable to capture changes to models. When using this package it doesn't create revisions for verifying the token (or creating it for that matter).

I have tried to get this working by changing the updateUser method in UserVerification.php which works, but this obviously is not going to work well

The reason the revisions aren't created is because the methods used are database rather than eloquent, revisionable listens for model events which are fired when for example $model->save() is called.

I tried:
```
  protected function updateUser($user)
  {
    $user = $user;
    $newu = new \App\User;
    $newu = $newu->find($user->id);
    $newu->verification_token = $user->verification_token;
    $newu->verified = $user->verified;
    $newu->save();
  }
```
which appeared to work however I would prefer the id column to not be hardcoded and use the $model->getKeyName() method - I couldn't seem to get this to work:

`$newu = $newu->find($user->getKeyName());`

Also not sure what to do about hardcoding the models' namespace, hoping you can help ;)

Is there a better way of doing this?

Why does this package use database as opposed to eloquent methods?

Any chance you could upgrade all methods to use eloquent?

**Comment by jrean** [comment]
Hi, thank you for your feedback.
I tagged your message so if anyone can/want to help you...
I close the this as it is not related to a package issue.

**Comment by robbielove** [comment]
Thanks for your response.

Are you able to answer: Why does this package use database methods as opposed to eloquent methods?

I might end up forking to make that change but it seems silly to do that just for a minor change and then merge updates each time you make changes...
