### ISSUE TITLE
Publishing lang need fix

### ISSUE THREAD

**Issue by mohamedsabil83** [jrean/laravel-user-verification#185]
When publishing lang, it's saved in `resource > lang > vendor > laravel-user-verification` but doesn't read until I move `en` folder from there to `resource > lang`.

**Comment by jrean** [comment]
Hi @mohamedsabil83, thank you for the feedback. What version of the package do you use?

The documentation of the package is pretty clear:

Translations:
To customize the translations you may publish the files to your resources/lang/vendor folder using the following command:

`php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider" --tag="translations"`

This will add `laravel-user-verification/en/user-verification.php` to your vendor folder. By creating new language folders, like `de` or` fr` and placing a `user-verification.php` with the translations inside, you can add translations for other languages.

https://laravel.com/docs/5.6/packages#translations

You don't need to move anything.

Hope that will help you.

Cheers,
