### ISSUE TITLE
Token Expiry 

### ISSUE THREAD

**Issue by k-zafar** [jrean/laravel-user-verification#187]
Hi,
Thank you for nice package. 

Can you please update plugin with feature to expire token after 24 hours?

Thanks!

**Comment by Konafets** [comment]
Check out my PR #179

**Comment by k-zafar** [comment]
@Konafets Thank you very much for this. Im new to Laravel so now how can I get this pull request to laravel code using composer. So that my team get the code easily and I can update site/server as well.

Thanks!
