### ISSUE TITLE
Configuration and views could be provided

### ISSUE THREAD

**Issue by vpratfr** [jrean/laravel-user-verification#19]
Would be nice to be able to have a configuration to indicate the path for the views.

By default they are `errors.user-verification` and `emails.user-verification` which may not be convenient depending on how the project structures its views.

Here is a quick draft. That should be trivial to add.

```php
/** config/user-verification.php */
return [
  'views' => [
    'email' => 'emails.user-verification',
    'error' => 'emails.user-verification',
  ],
];
```

```php
    /** src/UserVerificationServiceProvider.php */
    public function register()
    {
        $this->mergeConfigFrom(
            dirname(__DIR__) . '/config/user-verification.php', 'user-verification'
        );
    }
```

```php
    /** src/UserVerificationServiceProvider.php */
    protected function emailVerificationLink(AuthenticatableContract $user, $subject, $from = null, $name = null)
    {
        return $this->mailer->send(config('user-verification:user-verification.views.email'), compact('user'), function ($m) use ($user, $subject, $from, $name) {
            if (! empty($from)) {
                $m->from($from, $name);
            }
            $m->to($user->email);
            $m->subject(is_null($subject) ? 'Your Account Verification Link' : $subject);
        });
    }
```

**Comment by vpratfr** [comment]
You could then override that setting by doing that in your project:

`php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider"`

**Comment by vpratfr** [comment]
And here is a package I made which has custom views and config, both publishable for customization:

https://github.com/marvinlabs/laravel-setup-wizard

**Comment by jrean** [comment]
@vpratfr thank you for the feedback. The configuration file is coming with the next release (soon).

Now you can already change the error view by overriding the `$verificationErrorView` which by default is `$verificationErrorView = 'errors.user-verification';`

I will push a hotfix to allow one to customize the email view while I'm preparing the next release.

Thank you for the inspiration. I will give a look later today.

Cheers

**Comment by jrean** [comment]
@vpratfr 
https://github.com/jrean/laravel-user-verification/releases/tag/v2.2.14

You can now customize the view name:

```
        UserVerification::generate($user);
        UserVerification::emailView('emails.foo');
        UserVerification::send($user, 'This is the cool subject');
```

If you want to customize the error view name, override the `$verificationErrorView` propertie/attribute which by default is `$verificationErrorView = 'errors.user-verification';`

The next release is coming soon with a refactored config implementation.
Thank you

**Comment by vpratfr** [comment]
Nice. Thanks a lot. I'll wait for the config release. Great news.
