### ISSUE TITLE
problem with TokenMismatchException

### ISSUE THREAD

**Issue by fake-fur** [jrean/laravel-user-verification#199]
hi again

i have the following in my handler.php:

`if ($exception instanceof \Jrean\UserVerification\Exceptions\TokenMismatchException){
	return redirect()->route('user.notverified.fail',['id' => $request->user()->id]);
} else if ($exception instanceof \Jrean\UserVerification\Exceptions\UserNotVerifiedException){
	return redirect()->route('user.notverified',['id' => $request->user()->id]);
}`

but the TokenMismatchException never gets triggered, even when i deliberately "break" the token - any ideas why that would be?

**Comment by berry807** [comment]
Same issue here. Looks like `verifyToken($storedToken, $requestToken)` is overwriting the exception path
