### ISSUE TITLE
Allow working with named routes rather than direct URLs

### ISSUE THREAD

**Issue by vpratfr** [jrean/laravel-user-verification#20]
Using direct URLs is according to a lot of people bad practice: 

- when you change a URL you don't want to have to look all over the code, but instead just in a single place, the `routes.php` file.
- it makes it difficult to add localized routes (different path for different languages)
- etc.

This is why named routes are used. Currently, all the redirections you provide are using direct URLs instead of named routes. Would be nice to be able to use route aliases.

**Comment by jrean** [comment]
Hi,

Thank you. You miss understand the package. The routes are not part of the package. It is just a sample and easy implementation into the documentation to get started. You are free to declare the routes you want and so to use route names. You just need to call the package needed methods (as stated into the documentation)
I hope it is more clear.

Cheers

**Comment by vpratfr** [comment]
That's part of your trait indeed. And that trait provides a good basic implementation. You could however make it a bit more flexible/configurable. For example:

```php
trait RedirectsUsers
{
    /**
     * Get the redirect path if the user is already verified.
     *
     * @return string
     */
    public function redirectIfVerified()
    {
        if (property_exists($this, 'redirectIfVerifiedRoute')) return route($this->redirectIfVerifiedRoute);
        if (property_exists($this, 'redirectIfVerified')) return $this->redirectIfVerified;

        return '/';
    }
```

Else, if the purpose of the Trait is just a "demo", better not include it in the package directly, just in the documentation. 

If you provide something however, make it usable for a wide range of use cases.

**Comment by jrean** [comment]
The trait is not part of the demo. It is part of the package. The two routes that hit the trait methods (end points) are totally customizable. They show a sample of implementation and so you are free to write the routes you want. You just need to require/use the trait into the targeted controller.

**Comment by jrean** [comment]
Ah I just understood what you are talking about!! I thought you mentioned the getVerification route and the getVerificationError route...

You are talking about the redirect attributes!! Ok got it. Thank ;-)
Will give a look this weekend.
