### ISSUE TITLE
user password is reset when verified

### ISSUE THREAD

**Issue by fake-fur** [jrean/laravel-user-verification#200]
hi again

is this package resetting the user password when the verification process is complete and the user is updated to "verified" ?

mine seem to be being changed at this point

**Comment by DariusIII** [comment]
I am using this package for some time now and have not witnessed such a behavior.
If you could post the code you are using, maybe we could help pin the issue.

**Comment by fake-fur** [comment]
yes sorry for the delay - i figured this out and forgot to close this issue - closing now
