### ISSUE TITLE
Laravel Email Verification

### ISSUE THREAD

**Issue by yoeriboven** [jrean/laravel-user-verification#204]
I feel like I'm missing something here.

Laravel does email verification [out of the box](https://laravel.com/docs/master/verification).

What does this package add that Laravel doesn't have already?

**Comment by yoeriboven** [comment]
@jrean It is rather rude to just close an issue instead of answering the question.

**Comment by jrean** [comment]
Hi @yoeriboven 
If you look at the history of the package (branches / tags) you'll notice this package existed way before Laravel introduces this "out of the box" in the code base.
