### ISSUE TITLE
Class App\Http\Controllers\Auth\Request does not exist

### ISSUE THREAD

**Issue by circuit-monkey** [jrean/laravel-user-verification#21]
I've been following the instructions for your user email verification package. Installing via composer and adding service provider/alias/migration/views/routes have been very straightforward, but the part that is very confusing for me is editing AuthController.php. Here is the sample code in the directions: http://paste.ee/p/AjQSB and here is my own code so far: http://paste.ee/p/5ba7e "ReflectionException in Route.php line 286: Class App\Http\Controllers\Auth\Request does not exist" is the error that I am currently getting when I try to register a user. The other part that is not totally clear to me is when the directions say that "The model representing the User must implement the authenticatable interface Illuminate\Contracts\Auth\Authenticatable which is the default with the Eloquent User model." This is what my user table model currently looks like: http://paste.ee/p/ZdlyY

**Comment by jrean** [comment]
Hi @circuit-monkey,

`Class App\Http\Controllers\Auth\Request does not exist` ; the message is pretty clear. You need to import (use) the `Request` class.
Both `postRegister(Request $request)` and `register(Request $request)` need it as parameter.
In your sample code `http://paste.ee/p/5ba7e` you don't import (use) that class. So by default when the code runs it tries to load the Request class into the current namespace which is `App\Http\Controllers\Auth and of course that class doesn't exist.

To solve this issue, simply import (use) `use Illuminate\Http\Request;`.

Regarding your question for the model, as stated in the documentation, the model must implement (extend) the `Authenticatable` interface. It's done by default with the User model so your code is good.
 
```
use Illuminate\Foundation\Auth\User as Authenticatable;
 
class User extends Authenticatable
{

}
```

As you can see your User model is extending the `Illuminate\Foundation\Auth\User` aliased as `Authenticatable`.

This class is implementing the `AuthenticatableContract` (interface). All good.

```

https://github.com/laravel/framework/blob/2a38acf7ee2882d831a3b9a1361a710e70ffa31e/src/Illuminate/Foundation/Auth/User.php

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
```

Cheers
