### ISSUE TITLE
What is difference with built-in Laravel verification function?

### ISSUE THREAD

**Issue by lovecoding-git** [jrean/laravel-user-verification#211]
Thank you for such great package.

I am a bit confused.

What is difference between this and built-in laravel verification function?

Can anyone suggest me some blog or explanation about it?
Thank you

**Comment by masroore** [comment]
This package was used before built-in verification had been incorporated.
This package is no longer maintained actively. If you need verification for legacy laravel apps, use it. For newer versions, use the built-in functionality

**Comment by lovecoding-git** [comment]
@masroore  Thanks for your answer.

**Comment by jrean** [comment]
As mentioned by @masroore it was created a while ago when Laravel was not yet offering this feature.
