### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by Fossil01** [jrean/laravel-user-verification#212]
Any plans for Laravel 8 support?

**Comment by fake-fur** [comment]
if you do not plan on supporting laravel 8 so we all have time to migrate, could you put together some kind of migration guide? right now i am stuck not being able to upgrade as this package does not support laravel 8 and i really don't know how much work is involved in migrating over to native

thanks

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/pull/213
@fake-fur @Fossil01
