### ISSUE TITLE
Help with routing issue.

### ISSUE THREAD

**Issue by 0E800** [jrean/laravel-user-verification#23]
I have followed the instructions for setting up laravel-user-verification.

A test user fills out signup form, and is sent an email with a token link.

However, when test user clicks on token link they are redirected to error:
`NotFoundHttpException in RouteCollection.php line 161:`

What I am guessing is that when the user clicks on the verification link in the email its redirecting them somewhere that doesnt exist. Any guidance would be much appreciated.

**Comment by jrean** [comment]
Hi,

You must include the 2 routes described into the package documentation (and customize to your needs)(not mandatory)

Cheers

**Comment by 0E800** [comment]
Thank you so much for your quick response!

Here is my routes.php (you can see I have it added on Line 73, 74)
[](https://ghostbin.com/paste/q6ass)

Here is my AuthController.php
[](https://ghostbin.com/paste/tp637)

I can see in the AuthController.php that even before email verification, it still creates the user in the database. I really just want the verification token link that that new user receives to just take them to login. 

Really appreciate your help.

**Comment by jrean** [comment]
Hi @0E800 your ghostbin links are expired (404).
Did you manage to make it works?
If not, can you please re-share your code sample?

Cheers
