### ISSUE TITLE
Error during registration process

### ISSUE THREAD

**Issue by twoheadedmona** [jrean/laravel-user-verification#28]
I receive the following exception:
Maximum function nesting level of '100' reached, aborting!

This is my excerpt code from the register method (in AuthController.php):

        // Laravel > 5.2.7
        Auth::guard($this->getGuard())->login($user);

        UserVerification::generate($user);

        UserVerification::send($user, 'My Custom E-mail Subject');

        return redirect($this->redirectPath());

And this is my inclusion header:

```
namespace App\Http\Controllers\Auth;
use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;
use Jrean\UserVerification\UserVerificationServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
```

**Comment by jrean** [comment]
Hi @twoheadedmona,
Nothing wrong with your code, neither with the package. It's a server/env configuration issue.
Give a look at the entire thread.
https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting?page=4

Feel free to come back here and to comment if you fix your issue so you may help someone else.
Thank you.

Cheers.
