### ISSUE TITLE
User doesn't receive the verification email for Laravel 5.2.31

### ISSUE THREAD

**Issue by bathorus** [jrean/laravel-user-verification#29]
Hello,

Thanks for the wonderful work.
I tried to implement the code just like you gave in readme. This is my code for AuthController in Laravel 5.2.31.

```
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;
    use VerifiesUsers;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/';
    protected $username = 'username';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => ['logout', 'getVerification', 'getVerificationError']]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'username' => 'required|unique:users|min:3',
            'password' => 'required|confirmed|min:6',
            'email' => 'required|email|max:255|unique:users',
            'firstname' => 'required|min:2',
            'lastname' => 'min:2',
            'agreement' => 'required',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'username' => $data['username'],
            'password' => bcrypt($data['password']),
            'email' => $data['email'],
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
        ]);
    }

    /**
    * Handle a registration request for the application.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function register(Request $request)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $user = $this->create($request->all());

        //Auth::guard($this->getGuard())->login($user);

        UserVerification::generate($user);
        UserVerification::send($user, 'My Custom E-mail Subject');

        return redirect($this->redirectPath());
    }
}
```

But user doesn't receive the email for verification. Actually the mail is working for 'change password' and 'contact us' mail, so the mail should not have problem.
Could you please give me a solution? I'm completely new to this and I'm still trying my best to learn. Thanks in advance.

**Comment by jrean** [comment]
Hi @bathorus.
Thank you for the great Feedback.
Regarding your code sample, the implementation is correct!
On my side, I just tested the package with a Laravel 5.2.35 and it works.

- Do you receive any error message(s)?
- Did you properly update your database users table to add the 2 new columns?
- To be sure I understand properly what you encountered, you tried to register a new user, completed the form, submitted the form? Then what happens?
- Do you see the new user into the database?
- For the new user, do you see `0` as value for the column `verified` and the `token` for the `verification_token` column?

Last bu not least:
Into the `AuthController` class and the `register` method, replace the following (and try to register a new user):

```
UserVerification::generate($user);
```

by

```
dd(UserVerification::generate($user));
```

The `generate` method returns a `boolean` so you should get `true` as output.

Then replace the following and register a new user:

```
UserVerification::send($user, 'My Custom E-mail Subject');
```

by

```
dd(UserVerification::send($user, 'My Custom E-mail Subject'));
```

The `send` method returns a `boolean` so you should get `true` as output.

If you get `true` for both tests, it means it works.
My question will be "Are you sure you give an e-mail address you own and have access to?"

Please answer the questions, share your results.
We gonna find :-)

Cheers,

**Comment by bathorus** [comment]
Hi, @jrean,

Thanks for the response. Actually I don't want to let the user login if they haven't verify their email account. Could you explain how do I do that?

For your questions:
What version of the package did you installed? 2.2.18 or 3.0.0?
I use version 2.2.18 for Laravel 5.2.

Do you receive any error message(s)?
**No. There's no error. It works fine. It just won't send the email.**

Did you properly update your database users table to add the 2 new columns?
**Yes, just like the tutorial.**

To be sure I understand properly what you encountered, you tried to register a new user, completed the form, submitted the form? Then what happens?
**I want them to verify their email first in order to be able to login. If they try to login before verify the email, the system will resend the email. How do I do that?**

Do you see the new user into the database?
**Yes, the new user is in database after registering, with verified 0 and verifiedtoken filled.**

For the new user, do you see 0 as value for the column verified and the token for the verification_token column?
**Yes**

I tried both `dd(UserVerification::generate($user));` and `dd(UserVerification::send($user, 'My Custom E-mail Subject'));` one by one, and it all returns `true`.

Then It must be something wrong with my mail config. But actually, when user forgot password, and ask for link to reset, the email is sent, and receive properly.
Here is my `.env` for mail:
```
MAIL_DRIVER=mail
MAIL_HOST=asdasd.com
MAIL_PORT=10
MAIL_USERNAME=hello@asdasd.com
MAIL_PASSWORD=***********
MAIL_ENCRYPTION=tls
```

I appreciate your help. Thank you.

**Comment by jrean** [comment]
@bathorus 
Regarding the issue with the e-mail.
- You confirmed with the two booleans returned the package works properly and the e-mail is sent.

Please try to use the e-mail log driver and check your logs to see the trace.
https://laravel.com/docs/5.2/mail
(Alternatively, you can also use Mailtrap.io service to catch all e-mails of your App)
Please share the logs.

- Did you properly create the e-mail view file as mentioned within the documentation?

> Actually I don't want to let the user login if they haven't verify their email account. Could you explain how do I do that?

Easy, you can just write a test that check if `$user->verified == 1` or `0`. Then allow or not the user to log in.
Alternatively, you can create a middleware with the same test and use the middleware for your targeted routes.

**Comment by jrean** [comment]
Please continue to post until you find what is wrong so it will also help the community.
