### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mgkimsal** [jrean/laravel-user-verification#3]
There's loads of things that don't work, at least with 5.2.  The composer.json indicated this works with laravel 5.2, but... can't get it to work.

The example AuthController - shouldn't be 'postRegister' - it needs to be 'register'.  The $this-> in the traits seems to get confused maybe?

        Auth::login($user);
        UserVerification::generate($user);
        UserVerification::send($user, 'My Custom Email Subject');

These lines don't make any sense - there's no static methods for generate() or send() on UserVerification class.

Did this used to work on earlier Laravel?

**Comment by jrean** [comment]
@mgkimsal thanks for your comment.
`UserVerification::` is a Laravel Facade.
Please refer and follow the documentation for registering the Service provider and the Facade.

> Open up config/app.php and add the following to the aliases key:
> 'UserVerification' => Jrean\UserVerification\Facades\UserVerification::class

This package has been written for Laravel 5 & 5.1 and should work for 5.2.
I will check it as soon as possible.
On your side, please follow step by step the provided doc and give me your feedback.

J.

**Comment by mgkimsal** [comment]
I *have* followed the step by step guide, and it wasn't working, hence the issue.  Alias was already added.  

what I've learned is that phpstorm can't handle these 'facades' - showing a class method used statically when there's no static method on it was showing problems.

The registration works, but the verification doesn't.

    public function getVerification($token)
    {
        $user = auth()->user();


The $user is null.

Type error: Argument 1 passed to Jrean\UserVerification\UserVerification::isVerified() must be an instance of Illuminate\Contracts\Auth\Authenticatable, null given, 

Shouldn't the user be looked up by the verification token?

**Comment by MoreKoo** [comment]
I'm also trying to find a solution for 5.2 version. I tried this out and ended up similar issues. Would be great to get a working version. Anyway, thanks for the efforts, J :)

**Comment by jrean** [comment]
@mgkimsal @MoreKoo first thing first, thank you for your feedback and sorry for the delay!
I'm really sorry but it works. I will update the documentation and try to help you but I just installed a fresh 5.2 instance and followed step by step what the documentation says and it works. Maybe I forgot to describe something in the doc (I didn't touch the package code)

Very quickly here is what I did:

.env file
```
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=xxx
MAIL_PASSWORD=xxx
MAIL_ENCRYPTION=null
MAIL_ADDRESS=support@test.com
MAIL_NAME="Test Support"
```
Feel free to not use mailtrap...

config/mail.php
```
    'from' => ['address' => env('MAIL_ADDRESS'), 'name' => env('MAIL_NAME')],
```
Updated line 58 with this

routes.php
```
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::get('auth/verification/error', 'Auth\AuthController@getVerificationError');
    Route::get('auth/verification/{token}', 'Auth\AuthController@getVerification');
});
```
As stated by the documentation

AuthController.php
```

use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    use VerifiesUsers;

    public function __construct()
    {
        /* $this->middleware($this->guestMiddleware(), ['except' => 'logout']); */
        $this->middleware('guest', ['except' => ['getLogout', 'getVerification', 'getVerificationError']]);
        $this->middleware('auth', ['only' => ['getVerification', 'getVerificationError']]);

    }

    public function register(Request $request)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        Auth::login($this->create($request->all()));

        $user = auth()->user();

        UserVerification::generate($user);

        UserVerification::send($user, 'This is the cool subject');

        return redirect($this->redirectPath());
    }
```

Please tell me.

J.

**Comment by MoreKoo** [comment]
Thanks J! However this is a bit late for me, I ended up writing my own email verification logic on top of Laravel authentication package.

**Comment by haakym** [comment]
@jrean thanks for this package

I performed a fresh install for Laravel 5.2 and then installed your package, I followed the steps in the readme and the steps you details here https://github.com/jrean/laravel-user-verification/issues/3#issuecomment-194653107 and everything worked fine with the exception to the `logout`. I had to change the following in the `AuthController` constructor method:

```
$this->middleware('guest', ['except' => ['getLogout', 'getVerification', 'getVerificationError']]);
```
to 
```
$this->middleware('guest', ['except' => ['logout', 'getVerification', 'getVerificationError']]);
```

Hope this feedback is useful to you and look forward to seeing the package develop.

**Comment by haakym** [comment]
Some further observations:

As @mgkimsal alluded to, the user needs to be logged in for the verification to work. Guess it's not an issue if that's the intended behaviour, but it may help to make that clear to the user if they hit the verification URL and see the login form, then `redirect()->intended()` after they've logged in perhaps?

**Comment by jrean** [comment]
@haakym again, good catch!!

**Comment by jrean** [comment]
@haakym I will also check about the need or not for the user to be identified. I just thought about it and it seems not to be mandatory. It should even work in both cases. I will patch it. Thanks

**Comment by jrean** [comment]
@haakym the package has been updated.
Would you be kind to test it?
https://github.com/jrean/laravel-user-verification/issues/7

Cheers
