### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sobhanattar** [jrean/laravel-user-verification#32]
Adding these 2 feature can be so good:

1. Putting a config file so we can set valid verification period(for example 120 minutes from registering time). Now, It can be obtained by editing `update_at` field of users and `time()`; but having a config item to enable/disable this feature and setting the time for it, is a far better option. 

In addition if this option consider different types of `guards` (in case of using multiple authentication table - for admin and users for instance) it would be ground breaking.

2. Deciding if user can login or not based on a config item. Again this is controllable by a simple query, but I think putting it behind a simple config can produce more productivity and less code.

If you give me some hints - as I didn't write any library for Laravel till now - I can help :+1:

**Comment by jrean** [comment]
Hi,
Thank you for the great feedback.
I keep in mind your suggestions. An improved version is under development and will be released under the 3.0 branch. The config file is something I have in mind. Please note that for extra functionalities I'm still brainstorming. The only purpose of this package is "user e-mail verification" (the Laravel way as much as possible) and I reckon anything additional should not be managed by the package but by one's implementation.

:)
