### ISSUE TITLE
verification exceptions

### ISSUE THREAD

**Issue by fake-fur** [jrean/laravel-user-verification#33]
hi and thanks for this - really super helpful

i am having an issue with token mismatch but the token are in fact identical (i compared the email token to the database token) - is there anyway i can see what exactly the verification link params look like to the verification code? i cannot see a way to easily pass the exception object or data thru to the error view, unless i'm missing something

**Comment by jrean** [comment]
Hi @fake-fur,
Thank you for the feedback!

I admit, this is the first time ever I read this exception is thrown!
To help me help you, can you please provide the following (content):
- [x] Laravel version used
- [x] Package version used
- [x] `resources/views/emails/user-verification.blade.php` or wherever you created that view
- [x] `app\Http\Controllers\Auth\AuthController.php` or `app\Http\Controllers\Auth\RegisterController.php` depending on the version of Laravel you use.

Thank you

**Comment by fake-fur** [comment]
hi again @jrean 
thanks for getting back to me - it was completely my fault and i feel silly now

i was using nginx with laravel and had the rewrite rules wrong in a way that things mostly worked but didn't allow the email param to be passed thru to the verification code (4hrs of hair pulling to find i'm stupid :) )

i will close this issue and apologise again

**Comment by jrean** [comment]
@fake-fur 
It's great you found the issue.
Thank you for participating. Come back here anytime if needed.
