### ISSUE TITLE
Include migrations, email template & add facade to service provider.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#34]
Hey, as of laravel 5.3 you can ship migrations that can be execute from within the package directory: https://www.laravel.com/docs/5.3/packages#migrations

I think this would be very beneficial for the packages to add those, at it makes the setup a lot easier.

Also you could register the facades in the service provider, this would reduce another setup step.

```php
  public function register()
  {
        $this->app->booting(function()
        {
            $loader = \Illuminate\Foundation\AliasLoader::getInstance();
            $loader->alias('UserVerification', 'Jrean\UserVerification\Facades\UserVerification');
        });
}
```

Additionally an email template would be awesome. You can make it publishable in laravel 5.3 like so: https://www.laravel.com/docs/5.3/packages#public-assets

**Comment by jrean** [comment]
I will review your PR.
Thank you
