### ISSUE TITLE
Create test-suit

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#36]
I think it would be awesome if you could add a test suit, this would make contributing much easier, as travis could immediately tell you when you broke something.

**Comment by jrean** [comment]
Agree.
Thank you

**Comment by lukasoppermann** [comment]
Sorry to open this conversation again, but are you actively working on this? I just notice that it would be pretty helpful when submitting PRs, because I would not need to test it in the framework, just run the test suit and you would have automated tests as well.

Another benefit of adding this soon, would be, that people who send PRs with new features, will be able to provide tests for the features as well, so you do not have to write all tests. 

If you start the test suit covering some of the basic functionality I can send some PRs to add more tests for some of the features I PRed.

Also you could us something like http://coveralls.io to make a PR fail if the test coverage goes down to much (e.g. people submit lots of code, but no tests) and of course http://travis-ci.org can automatically check tests, so errors in a PR can be spotted by the system.

**Comment by jrean** [comment]
@lukasoppermann please send me an e-mail at go@askjong.com
Thank you
