### ISSUE TITLE
Add default template for error page.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#38]
I think a default template for the error page should be shipped in the package. Maybe the user could even publish it and use it to create a custom one, but if the user choses not to, a default one should be shown.

**Comment by jrean** [comment]
Agree.
Thank you

**Comment by lukasoppermann** [comment]
Hey, why are you closing all the issues? Shouldn't they stay open until this is actually implemented?

**Comment by jrean** [comment]
It's a small package. I keep track of everything, requests, ideas, ...
I try to keep the "opened" section empty. No offences

**Comment by lukasoppermann** [comment]
Ahh, okay, its just that people might re-create an issue, as they do not see it and have no idea what you are working on.

Maybe it would be a nice idea to leave the there for that purpose, as you tag them in any case?

**Comment by lukasoppermann** [comment]
Hey @jrean are you still working on this? Could you please, please, please only close issues that you either solved, or close because you are not working on them? 

You closing everything is very confusion, because nobody knows what you are still working on, considering, etc. 

People can not know for which issues they should send PRs, etc.

**Comment by lukasoppermann** [comment]
True, sorry, I mixed that up, the email template is not included.
