### ISSUE TITLE
change in users table primary key

### ISSUE THREAD

**Issue by aqib-git** [jrean/laravel-user-verification#45]
If we change primary key name other than "id" the user verification doesn't work because your hard coding table primary key in getUserByEmail function inside UserVerification.php file.

**Comment by jrean** [comment]
Thank you for the feedback. Nice catch!
I will patch the source later today.
It will return `first()` instead of `first(['id', ...])`.

**Comment by aqib-git** [comment]
Thankyou

**Comment by jrean** [comment]
@aqib-git 

https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.5

Can you please give a try and tell us if you are happy with that?
