### ISSUE TITLE
Resend verification

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#46]
I would like to offer the option to resend a verification email with the old or a new token. A user should just click a link. Can you add this functionality? I guess it would need to be another get route.

**Comment by jrean** [comment]
Hi @lukasoppermann 
Thank you for the feedback.
To achieve what you want, simply call anytime 

```
UserVerification::generate($user);
UserVerification::send($user, 'My Custom E-mail Subject');
```

And it will regenerate a token, change the status to `0` and send again an e-mail.

So you are free to implement a new route. This package only provides the core functionalities to achieve the verification.

I let you close this issue ;-)

Cheers.

**Comment by lukasoppermann** [comment]
Perfect, I must have not seen that in the readme, thanks.

**Comment by nicholascourage** [comment]
I'm having difficulty with this as I've called it in
```
public function resendVerification(){

        $user = Auth::user();

        UserVerification::generate($user);

        UserVerification::send($user, 'My Custom E-mail Subject');

        return redirect($this->redirectPath());

    }
```
I've used the directives:

```
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Traits\UserVerification;
```

But keep getting a 500 error of Call to undefined method Jrean\UserVerification\Traits\UserVerification::generate()

**Comment by nicholascourage** [comment]
I realized my school boy error - I didn't reference it as a facade ie. use:

`use Jrean\UserVerification\Facades\UserVerification;`

instead of 

`Jrean\UserVerification\Traits\UserVerification;
`
 Confusing because the documentation says to use this for regenerating the email verification link?
