### ISSUE TITLE
Add routes to package

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#47]
Hey, currently the user has to set the routes in their routing file. I think it would be much nicer, if the package would define the routes by default.

Like so: https://laravel.com/docs/5.3/packages#routing

If you would be interested I could send a PR with this change.

**Comment by jrean** [comment]
Great idea.
Please send a PR (if it can't be compatible for 5.3 / 5.2 / 5.1 / 5.0 please send separate PR)
If we provide routes by default we must allow users to override / extend / customize.

Thank you

**Comment by lukasoppermann** [comment]
Overwriting routes is easy, as long as the user adds the service provider with all other package service provides **before** the app `RouteServiceProvider`. (I will make sure to add this to the readme.)

Also I would like to change the routes. Can we change them to `email-verification/error` and `email-verification/token`? This way they would be more specific and the chances of a user needing to overwrite them would be lower.

(Verification would mean something else but email in other apps.)

**Comment by jrean** [comment]
Ok. Great. I agree with the route names. It won't break backward compatibility so it's ok.
