### ISSUE TITLE
Verification doesn't works

### ISSUE THREAD

**Issue by jodypati** [jrean/laravel-user-verification#5]
The verification doesn't work, only work for logged in user

public function getVerification($token)
{
    $user = auth()->user();

The $user is null.

Type error: Argument 1 passed to Jrean\UserVerification\UserVerification::isVerified() must be an instance of Illuminate\Contracts\Auth\Authenticatable, null given,

Shouldn't the user be looked up by the verification token?

**Comment by damarev** [comment]
Same issue here, on Laravel 5.2

Also same conclussion @jodypati points:  auth()->user() returns null if no user is logged.

I searched the package code to find the spot where the user is looked up by the token, but no luck...

**Comment by damarev** [comment]
Changed this

```
public function getVerification($token)
{
        $user = auth()->user();
```

into

```
public function getVerification($token)
{
        $userClassName = auth()->getProvider()->getModel();
        $userModel = new $userClassName;
        $user = $userModel::where('verification_token', $token)->first();

        if(!$user){
            $this->verificationErrorView();
        }
```

And now it works as expected. Although I think I am missing something...

**Comment by damarev** [comment]
Now I understand. This error shows up because in the AuthController i just have:

```
    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout', 'getVerification', 'getVerificationError']);
    }
```

instead of

```
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['getVerification', 'getVerificationError']]);
        $this->middleware('guest', ['except' => 'logout', 'getVerification', 'getVerificationError']);
    }
```

My mistake, didnt understand that the auth/only was also required for laravel 5.2

Does this means that the process of confirming a user, requires that this user must be already logged? I have overrided the register method in my AuthController like this:

```
    public function register(Request $request)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $user = $this->create($request->all());

        UserVerification::generate($user);
        UserVerification::send($user, 'My Custom Email Subject');

        //Auth::login($user);

        return redirect($this->redirectAfterRegister);
    }
```

because I don't want to allow a user to log in until it has confirmed his account first (I am trying to avoid spam accounts).

Could this functionality be implemented in the future? I think it would require to generate the activation link paired with the user email, like /auth/verification/[TOKEN]?email=[USER_EMAIL]

**Comment by jrean** [comment]
Hi guys, @jodypati, @damarev,
Thank you for your feedback.
Let me clarify, by default, yes, this package has been thought to follow the default register flow.
- User register
- User is automatically logged in
- User has to confirm his email and to be logged in for that.

You are not the first one to mention this so I will spend time this weekend to update the package and to modify the behaviour.

J.

**Comment by jodypati** [comment]
thanks @damarev it works well now, 
@jrean I hope it can be more flexible to another flow, I'll glad to wait for the update

**Comment by jrean** [comment]
@jodypati I will hack something asap this weekend

**Comment by jrean** [comment]
@jodypati 
I just updated the package.
Would you be kind and test it?
https://github.com/jrean/laravel-user-verification/issues/7

Cheers
