### ISSUE TITLE
Dry up email sending code.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#53]
Hey @jrean,

this seems to be nearly exactly the same code:

https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L332-L339
https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L354-L361
https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L377-L384
https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L400-L407
https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L423-L430

This could be probably refactored into a function and the parts that differ could be moved into the functions above e.g. the `sendLater` function.  This would reduce much code and make it easier to understand, maintain and refactor.

**Comment by jrean** [comment]
Agree
