### ISSUE TITLE
Use a lang file.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#54]
Hey,

I think it would be good to add a language file for all the text and move it out of the code, for example here: https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerification.php#L430 but also here: https://github.com/jrean/laravel-user-verification/blob/master/src/resources/views/user-verification.blade.php#L9-L17

This would:

1. make it easier to customize the text without calling all the functions yourself
2. Make it easier to add multi-language support, by using your own language files.

We could make the language file publishable by the artisan publish command as well, I think.

Let me know if you like the idea and I will send a PR.

**Comment by jrean** [comment]
Agree

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.8
