### ISSUE TITLE
Add migration to package.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#55]
Hey, as of laravel 5.3 you can ship migrations that can be execute from within the package directory: https://www.laravel.com/docs/5.3/packages#migrations

The user does not even have to export them. I think it would be a very nice addition for the user to add this. One less step to install this package.

**Comment by jrean** [comment]
I totally agree.
We can implement it first for the 5.3 and then check compatibility with 5.0-5.2

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.10
