### ISSUE TITLE
Move master to 5.1

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#57]
Hey,

I think it might be a good idea to change the master branch to be Laravel 5.1, becasue:

1. 5.1 is the LTS release which makes
2. Upgrading is pretty similar and if people can't upgrade because of their php version < 5.5.9 they can't use this package in any case.

Instead of having the master support 5.0 you could, if you wanted to, have a 5.0 branch an backport stuff.

**Comment by jrean** [comment]
Hi.
I understand your idea but I will keep the current branching. Thank you

**Comment by lukasoppermann** [comment]
Ahh, I forgot the most important point, 5.0 is very different in many things concerning package publishing stuff, etc.
