### ISSUE TITLE
Move token & verified to separate table

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#58]
I think the `token` and  `verified` column should be moved from the user table and put into a separate table just like the password reset table, with an email address and a created_at. This would mean there is not need to change the user-table, which might be a bit of an issue if the package is added later on. See: #71 

This would:
- open up the way to extend this to verify multiple email addresses for one user
- open up the possibility of extending this to verifying other things later on, like phone numbers
- make it easy to know when an activation link was sent, this is very important if you want to show the user an alert like: "Please verify your email address [resend]" and when the user clicks resend, you want to NOT show the alert for X hours, because they just resent the alert.
## Configuration
- a section in the config file from #69 should be added to allow the user to specify the name for the `user_verification` table. This is just a fallback in case a `user_verification` table exists already.

**Comment by jrean** [comment]
I really want to think about this one before going further. The idea is great. I already thought about it many times.

**Comment by lukasoppermann** [comment]
Of course, I think this package could be made much more flexible with this approach, but it does need some thought first. 👍

**Comment by fake-fur** [comment]
again please remember to update the documentation as well

**Comment by jrean** [comment]
@fake-fur this is always on top of my priority. Keeping the documentation clear is mandatory. I reckon we do our best. Don't worry. Following simver, all minor updates won't break backward compatibility.

**Comment by lukasoppermann** [comment]
Another problem solved by this: #75

**Comment by hakimihamdan88** [comment]
any update guys?

**Comment by hiddenicon** [comment]
Any update on this feature? I'd like to see something like it as well. It would also help to set an expiration for a verification token as if the user never does it you can remove it from the table.
