### ISSUE TITLE
isVerified and verificationPending via Trait.

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#62]
Hey,

I think it could be a nice addition to create a trait that you can add to your `User` model which introduces 2 new methods:

- `isVerified` will return a boolean by checking if the verified column is `1`
- `isPending` will return a boolean by checking if
  - user `isVerified` 
  - if not verified, it checks if a token is present

While those functions are not hard to write yourself, I think they can be very useful and its a nice convenience addition.

**Comment by jrean** [comment]
Agree. Anyway it will be additional and not mandatory.
You make a PR?

**Comment by lukasoppermann** [comment]
Sure

**Comment by fake-fur** [comment]
again this clashes with existing code for something entirely trivial to implement - is it really necessary? is this going to become one of those complex monsters that try to do everything instead of the clean simple solution to a singular issue that it started out as?

**Comment by lukasoppermann** [comment]
Why would it clash with any code at all? Its a trait, you are free to just not use it if you do not want. It will not be use automatically.

**Comment by fake-fur** [comment]
if we have implemented our own fns called the same names, since those names make sense

**Comment by lukasoppermann** [comment]
@fake-fur this will be no problem. If you leave everything "as is" you will not run into any issues. The trait is by default **NOT** used. So it is just a couple bytes in your HD. 

Of course, should you choose to use it, it will be a problem if the names are in use, but why would you want to use it if it is already implemented in your system? And if you would, you would probably remove your implementation.

**Comment by fake-fur** [comment]
these are reasons for upgrade docs no?

**Comment by lukasoppermann** [comment]
Of course, the documentation has to be and will be updated for every change.

**Comment by fake-fur** [comment]
OK cool thanks

**Comment by jrean** [comment]
Adding such trait won't create any clashes. It will be optional and will offer out of the box something often requested. We (I) take care of this package to not become a monster but a smart and wise one.
