### ISSUE TITLE
Use Laravel Register event

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#67]
Exciting news, the registerEvent I asked for, was just merged into Laravel: https://github.com/laravel/framework/pull/15401#event-792389164 and I hope it will be tagged soon.

We should take advantage of this!

My idea is the following:
1. Add a `config` file to the package
2. Add an option: `onRegistration` or something similar (`true` by default)
3. Whenever the register event fires, we automatically create the token and send out the email to the user as long as the config `onRegistration` is true.
   If it is `false` we do nothing.

This means the user will not need to add anything to the `AuthController` once I finish the `resend` PR with the move to the Controller!

However this will need to be a `minor` update. It is not really a breaking change, but if you just upgrade the system might send 2 emails (because you send on in the `AuthController`).

This will make the installation even easier and maintaining it as well, as we do not have to worry about `AuthController` changes.

@jrean What do you think?

**Comment by jrean** [comment]
It's awesome!
About the config file this is something I strongly want to implement so we can add all available configs into it (such as redirection routes and Co.)
Let's implement it for 5.3 :-)
Depending on the implementation I will see if I tag a major update or not.
Thanks a lot!

**Comment by lukasoppermann** [comment]
Yeahh, it has made it into Laravel `5.3.10` so we can start implementing this for the `3.0` branch.

**Comment by fake-fur** [comment]
hey guys

all these changes sound fabulous but now my site is broken - i cannot even create it from scratch because the migrations are now broken - is the documentation for this situation existing somewhere?

thanks

**Comment by lukasoppermann** [comment]
Hey @fake-fur this PR has not been merged yet, can you identify which change broke your site?

**Comment by fake-fur** [comment]
this happened running migrations on empty database

 [Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified' (SQL: alter table `users` add `verified` tinyint(1)
not n
  ull default '0', add `verification_token` varchar(255) null)
  [PDOException]  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified'

**Comment by lukasoppermann** [comment]
@fake-fur moved here: https://github.com/jrean/laravel-user-verification/issues/71

**Comment by fake-fur** [comment]
thanks

**Comment by groundbreaker08** [comment]
is this implemented also in 2.2?

**Comment by jrean** [comment]
@groundbreaker08 `2.2` branch is for Laravel <5.3 and the register event is not implemented.
So no, it's not implemented in 2.2
