### ISSUE TITLE
Leaving user logged out after registration

### ISSUE THREAD

**Issue by Chalkin** [jrean/laravel-user-verification#7]
Hi,

I would like to keep the user logged out after registration and sign him in after he verified his e-mail.

So i removed the "Auth::login($user);" from the postRegister(Request $request) function. But now the auth()->user does not return a user. (Since the user is not logged in) (btw. I somehow could not overwrite the postRegister method and had to use the register method - don't know why?!)

So what's in your opinion the best way to make this possible with your package? Should we get the user with the User Model and find the entry with the corresponding verification_token?

**Comment by jrean** [comment]
Hi @Chalkin thank you for your feedback.
Until the next update you "must" get the user logged in prior to verify the e-mail.
It will be changed and updated soon to allow more flexibility.
Look at this workaround:
https://github.com/jrean/laravel-user-verification/issues/5

About the `postRegister` method it's weird! Which version of Laravel do you use?
For Laravel 5.0, 5.1 & 5.2 we overwrite the `public function postRegister(Request $request)` in the `AuthController.php` file.

Cheers

**Comment by jrean** [comment]
So...
The first thing I would like to share is about the default behaviour of Laravel 5.0 / 5.1 / 5.2:

[postRegister() 5.0](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Auth/AuthenticatesAndRegistersUsers.php)

[postRegister() 5.1](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Auth/RegistersUsers.php)

[register() 5.2](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/RegistersUsers.php)

The `postRegister` / `register` method log the user in:
5.0 => `$this->auth->login($this->registrar->create($request->all()));`
5.1 => `Auth::login($this->create($request->all()));`
5.2 => `Auth::guard($this->getGuard())->login($this->create($request->all()));`

That said, I built this package with that in mind without thinking one would like to change this default behaviour. My bad. I think if I want this package to be totally agnostic it should just be able to work without any user logged in.

It means it's probably time for a rewrite and so a version 1.0!

Do you have any comments?

**Comment by Chalkin** [comment]
thanks a lot for the quick response.

I'm gonna check out the register() thing. I'm using Laravel 5.2
I will keep the user logged in after registration for now. But I can't wait until you update that :)

thanks a lot!

**Comment by jrean** [comment]
@Chalkin I just commited the update in the **release v2.0**.
The package works now without the need of an authenticated user.
Can you please find the time to test? I updated the documentation too.

Cheers

**Comment by Chalkin** [comment]
Yep, works now! It's a looooong verification token now. 
I probably would have done it another way. But both work.
- Check if the user is authenticated
- If not, i would have gotten the user via the passed verification token

Don't know which way is better.

One thing is still wrong in the documentation.
"Click here to verify your account {{ url('auth/verification/' . $model->verification_token) }}"
needs to be
Click here to verify your account {{ url('auth/verification/' . $user->verification_token) }}

Thanks a lot for changing your package!

**Comment by Chalkin** [comment]
Just tried to login the user after verification is complete. It does not work with Auth::login($user);

"Argument 1 passed to Illuminate\Auth\SessionGuard::login() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of stdClass given"

So i tried to use the Code suggested in https://github.com/jrean/laravel-user-verification/issues/5 from damarev and now it's possible to log the user in. (slightly changed)

`protected function getUserByEmail($email, $table)
    {
        $userClassName = auth()->getProvider()->getModel();
        $userModel = new $userClassName;
        $user = $userModel::where('email', $email)->first();

        // Already verified
        if($user->verified) {
            // todo - do something
        }

        $user->table = $table;

        return $user;
    }`

**Comment by jrean** [comment]
@Chalkin thank you for the feedback.
The code is still under review and will probably be updated but please let me clarify some details for us.
The wish was to not be tied to to the authentification flow anymore. It is.

- The token is long.
Yes, it's, but is it an issue? I don't think so. I used what Laravel offers us. `Crypt` (AES-256-CBC).
I tried to be smart because I knew I will also need to get access to the email address so what I did is simple. I encrypt the email address which becomes the token and then later during the verification process I can just decrypt the token and get the email address.
https://laravel.com/docs/5.2/encryption

- `Auth::login($user)` doesn't work anymore.
Agree. I thought you guys may say one day!

> Hey, you designed the package with the User model in mind. What if I want to user another model instead!

So know the retrieved user is an instance of `stdClass`.

If you want to authenticate the user you may simply use the `Auth::loginUsingId($userId);`.
If you look at the content of the `stdClass $user` you will see the following:

```
{#233 ▼
  +"id": "13"
  +"name": "jean"
  +"email": "xxx@xxx.com"
  +"password": "xxxx"
  +"remember_token": null
  +"created_at": "2016-03-23 02:24:06"
  +"updated_at": "2016-03-23 02:24:06"
  +"verified": "0"
  +"verification_token": "eyJpdiI6Ilg3ZHgxZDV1eTNzaUJBZVZCWjUzNGc9PSIsInZhbHVlIjoiSGIycVBjUCtcL1d2bkJPY1lLdk5YZ3gzZklDbTh6TVwvTnFQcHdYWlozdDFjPSIsIm1hYyI6IjBiYWxxxhYjU5ODY3NmQzYzVjZGM3NzFlZDViMjJiOGMxODk2Mjk5ZDQyYWFmOWUwZmExY2FkODMwOTczZjIifQ=="
  +"table": "users"
```

Simply use the id and your are done.
I hope it will help.
I will check how to improve again.

Cheers
