### ISSUE TITLE
Migration Duplicate, Column already exists

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#71]
@fake-fur

```
this happened running migrations on empty database

[Illuminate\Database\QueryException]
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified' (SQL: alter table users add verified tinyint(1)
not n
ull default '0', add verification_token varchar(255) null)
[PDOException] SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified'
```

This means you already have the column in your table. Why do you try to run the migration again? Apparently your table is already set up. Did you alter your user table migration to include this verified field?

If so you should remove it from the `user table migration`.

**Comment by fake-fur** [comment]
when i was working with the earlier versions of the package i had to add the migrations - now they are broken and break what was a working site

this is why i was asking earlier about docs for the upgrade process, and docs towarn how to avoid this and other situations that will occur in the rush to the new shiny

**Comment by lukasoppermann** [comment]
I added a PR to clarify this. @jrean If we move to #58 and use a separate table we should not have problems with already existing values. This is beneficial because some other package could alter the users table.

@fake-fur I am sorry it broke for you, and I added something to clarify it. However, the section about adding a migration file has been removed. It is expected if you reinstall / re-migrate (part of the installation process) the package, that you start from fresh and go by the current docs.

It is very hard to anticipate all edge cases of users who already have part of the installation from an old version done. Would you have not re-run the migrations, you should have been alright.

Did you get it to work now, after removing the double migration?

**Comment by fake-fur** [comment]
but i have code that looks for the columns in that table - so now i have to rewrite that code too, and check all the places my code may have touched because of these changes that break an existing package by a simple "composer update"

honestly i fully understand the need to move forward and incorporate new features of the underlying platforms, but these should be done in a new version that is clearly separated and documented, otherwise people lose confidence in the package as being unreliable going forward, and then you may as well not write it in the first place

really disappointed this wasn't done more responsibly

**Comment by lukasoppermann** [comment]
No, the columns will be added. Why would you need to change your code? The problem is only the migration is run twice. The actual columns have not been touched at all.

**Comment by fake-fur** [comment]
from the documentation:

CONFIGURATION

Prior to use this package, the table representing the user must be updated with two new columns, verified and verification_token.

It is mandatory to add the two columns on the same table and where the user's e-mail is stored.

The model representing the User must implement the authenticatable interface Illuminate\Contracts\Auth\Authenticatable which is the default with the Eloquent User model.

*sigh*

**Comment by fake-fur** [comment]
but yes - removing them from my migration and re-running the migrations on an empty database did work

sorry for getting irritated but i work with stuff every day where "ooooh better" breaks working codebases often with no hints at how to fix them so i get sensitive around this issue for stuff that wants to be "core" to people's work

**Comment by lukasoppermann** [comment]
Hmm, I see, so you got confused, because it says this:

> Prior to use this package, the table representing the user must be updated with two new columns, verified and verification_token.

And only afterwards talks about the migrations, that actually do exactly this. I will edit my PR #72 and (re)move this part.

**Comment by fake-fur** [comment]
yes thanks - i'm sure if i was as good with laravel as you seem to be i would be able to cope with changes like these easily but when one is still learning it such changes can be confusing - again sorry if i came across as being rude or anything - totally wasn't my intention

**Comment by lukasoppermann** [comment]
I see how this can be complicated, but of course we still need to be able to update this package. If you would like to not update the packages and just use the version that you have implemented you can always just set it in your composer file. This would never update and always use 3.0.12

```php
"require": {
        "php": ">=7.0.0",
        "laravel/framework": "5.3.*",
        "jrean/laravel-user-verification": "3.0.12",
```

**Comment by fake-fur** [comment]
thanks for the info and yes of course the package must be able to be updated - 100% agree :)

**Comment by jrean** [comment]
Thanks @fake-fur for the feedback and sorry for the issue you encountered.
@lukasoppermann thank you for handling this. I'm very glad of all the energy you are bringing to the evolution of this package. As mentioned I will review all the PR this weekend and I will start to pull to master. I will tag all upcoming updates to a new version to avoid any complains.

We will do our best to make the configuration of this package as easy as possible and we will make the documentation even clearer.

@fake-fur you are welcome to contribute to the documentation. Send PR anytime but maybe wait a little bit as a lot of updates are coming soon. You could help by testing the new updates and send feedback or PR if you thing the documentation will need to be improved.

**Comment by jrean** [comment]
@lukasoppermann I suggest we add to the documentation a new section "Update" so we can add some hints / instructions / ... to follow when updating (major / minor) to take in consideration @fake-fur feedback.

What do you think?

**Comment by lukasoppermann** [comment]
Sounds like a good idea.

**Comment by xKairu** [comment]
Okay so I just went to update from 5.2 to 5.3, and this is the only issue I have now. The prior version required us to make our own migration, and now you include it. This is fine, but you've decided to load it rather than publish, so now I can't simply delete the published migration.

Removing my own created one will not work either, as I already have it with a timestamp in my migrations table in the database, so it's trying to migrate the new one from the package.

Even a configuration file entry that defaults to the migration being loaded would be great, but for now I have to stick to 3.0.8 or else everything falls apart.

What do you suggest? Stay on 3.0.8? Wiping any `verified` columns is not an option on a live site. :/

**Comment by jrean** [comment]
Hi @xKairu 
Thank you for the feedback.

> This is fine, but you've decided to load it rather than publish, so now I can't simply delete the published migration.

Documentation says:

> To customize the migration(s) to your needs, publish them with the following command:

```
php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider" --tag="migrations"
```

I'm not sure I fully understand your question.
Of course, staying on 3.0.8 is not a long term solution.
Let us help you and maybe learn on how to improve the package. I'm very busy these days but I will do my best. Maybe @lukasoppermann will be able to help as well.

Thank you

**Comment by xKairu** [comment]
Sorry I should have been more specific. By loading the migration, you're automatically loading it into the pending migrations here: https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerificationServiceProvider.php#L41

This means it's always going to be run, regardless of publishing. The only workaround I can think of is by publishing, then essentially running an empty migration.

**Comment by jrean** [comment]
Ok thank you for the light.
Can you explain what is your issue then? I'm not getting it.

> but you've decided to load it rather than publish, so now I can't simply delete the published migration

> Removing my own created one will not work either, as I already have it with a timestamp in my migrations table in the database, so it's trying to migrate the new one from the package.

Do you receive an error?

Thank you

**Comment by xKairu** [comment]
Yeah, I'm receiving this error like in the OP:

```
[Illuminate\Database\QueryException]
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified' (SQL: alter table users add verified tinyint(1)
not null default '0', add verification_token varchar(255) null)
[PDOException] SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'verified'
```

My migration that I made when installing initially on 2.X, is named `2016_07_14_123900_add_verification_to_users_table`, whereas the bundled migration is named `2016_09_13_070520_add_verification_to_user_table`, resulting in a doubled up migration that fails.

The issue is because you're forcing the migration to be loaded [https://github.com/jrean/laravel-user-verification/blob/master/src/UserVerificationServiceProvider.php#L41](here), rather than instructing the user to publish. This is fine for new installs, but upgrades will always fail.

**Comment by jrean** [comment]
Thank you for the great feedback!
Question: (tell me what do you think)

Into the migration file:

```
/**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table($this->getUserTableName(), function (Blueprint $table) {
            $table->boolean('verified')->default(false);
            $table->string('verification_token')->nullable();
        });
    }
```

What if the migration test `if` the column(s) already exist? Do you think it will solve the issue?

I also wish @lukasoppermann to participate as he nicely pushed a lot of PR recently.

I'm sorry you encounter such issue.
I wait a few days and I will fix the issue. By going back and removing the loading or by applying a patch.

Your thoughts are welcome.

**Comment by xKairu** [comment]
>What if the migration test if the column(s) already exist? Do you think it will solve the issue?

Yup, that should do it, but then you lose the ability to make changes to columns in the future, it's up to you how you want to go about it.

**Comment by jrean** [comment]
Ok.
Thank you a lot. I will work on it this week as soon as possible and fix it.
I reopen the issue.

**Comment by jrean** [comment]
@xKairu last question.
You have the error when you run `php artisan migrate` right? The global column?

**Comment by xKairu** [comment]
Yeah, just when migrating.

**Comment by jrean** [comment]
Ok. Thanks.
So to quickly fix your issue. Why don't you remove from your `migration table` the old migration and just simply re-run a `php artisan migrate`?

**Comment by xKairu** [comment]
If I go into my production database and remove the entry for my own migration, your force loaded one will still try to run and throw the error. Same with removing the class for my own migration.

The error is being thrown because I already have the database structure from a previous version that your new migration is trying to build.

**Comment by jrean** [comment]
Mmmm.
In the migration table, alter/update the migration column by replacing the name of the new "loaded" migration. It should fix it. It's ugly but at least should work.

**Comment by xKairu** [comment]
Great idea, didn't think of that. I'm not ready to push my 5.3 upgrade to production yet, but I'll keep that in mind when I do, thanks.

**Comment by jrean** [comment]
Great. Again sorry for that bad experience. I should have thought about it before tagging the version under the 3.0 branch...

**Comment by lukasoppermann** [comment]
@jrean If you could agree to move everything to a new table soonish, we could easily just check for existence in the migration.

The new table setup would need to be tagged well of course, but this would mean for everything where we would want to alter the table layout we would just do it for the branch with the new table.

This could be done for both, the 3.X branch and the 2.X branch.

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.14

**Comment by jrean** [comment]
Regarding the "new table". Let me first read/merge all the opened PRs and we will work on this if this is really the proper way of doing :-)
Thank you

**Comment by lukasoppermann** [comment]
@jrean yes. If you have any questions or want to discuss ideas for this, there is always this ticket: https://github.com/jrean/laravel-user-verification/issues/58
