### ISSUE TITLE
Move to using Laravel 5.3 Notifications on 3.0 branch

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#74]
For the 3.0 branch we should move to using the https://laravel.com/docs/5.3/notifications as discussed in other tickets.

This ticket is here to track the process.

**Comment by jrean** [comment]
Unless we can add beside what is currently working we should include this to the 3.1 branch.
Let's keep that in mind
Thanks

**Comment by lukasoppermann** [comment]
I think we should NOT try to add it besides the current solution. It would be better to add it as a replacement and add it to `3.1`.
