### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by darki73** [jrean/laravel-user-verification#75]
Just installed your package. Found out thats its unable to run migration due to the fact, that migration provided with the package dated on September 2016, my new user migrations is dated October 2016, so engine tries to migrate your file first and then mine files.

I'm running Laravel 5.3.

From here comes the error that there is no users table. Please, find time to fix this problem.

**Comment by lukasoppermann** [comment]
Hmm @jrean as a quick fix is it possible to just make the migration have a far future date? Or does it have to be a date between today and the past?

**Comment by darki73** [comment]
**Just my opinion:**
If possible, this module should check for users table first, if it is not found, then migration from this module should not be run, if there is a table in database, simply run the migration

**Comment by lukasoppermann** [comment]
@darki73 I think your suggestion would not be consistant as it would run the migration if the user migration is older than the alteration migration, but not if it is the other way around. My PR now simply removes the autoloading so you will need to run:

```
php artisan migrate --path=/vendor/jrean/laravel-user-verification/src/resources/migrations
```

Its in your hand to run it after you added the user table.

**Comment by darki73** [comment]
@lukasoppermann sure, your solution is much better since it will help to avoid migration over older users table. Plus, its easier to make 1 more step for the user than to think of logic to mitigate every possible case with existing migrations. Hope to see your PR approved soon so i'll be able to publish my app onto production server =)

**Comment by jrean** [comment]
@lukasoppermann thank you. This is what I was thinking about as well. I will review the PR now and merge it.

@darki73 Thank you for the feedback. I think "creating" a new `users` migration is a bad practice. You should `alter` the existing migration and so avoid this kind of issue. Because it may happen with other package as well.

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.14
