### ISSUE TITLE
Add route middleware for redirect on unverified

### ISSUE THREAD

**Issue by lukasoppermann** [jrean/laravel-user-verification#76]
Hey @jrean,

I think we should add an optional middleware, which if loaded checks if the user is verified and if not redirects the user to a specific page or something like this. 

The behaviour should probably be customizable as it depends on your app but I think the general **take an action if user is NOT verified** is a general concern for many people.

**Comment by jrean** [comment]
Agree. We can provide such default behaviour and check. I just don't want this package to take any direction into implementation. Just "user verification".

Can you draft a PR?

Thank you again.

**Comment by lukasoppermann** [comment]
Sure, I was basically thinking of either an empty middleware or something like the laravel 5.3 auth, where an exception is thrown and you can handle it in the new exceptions folder. I will check which one makes more sense and send a PR.

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.15
