### ISSUE TITLE
Method [getVerification] does not exist.

### ISSUE THREAD

**Issue by kinnedev** [jrean/laravel-user-verification#79]
I am getting this error when hitting the email-verification/check/ route: 

Method [getVerification] does not exist.

I am working with Spark and Laravel 5.3. I am sure its something I am doing wrong, but not sure. 

Any help would be appreciated. 

Thank You!

**Comment by lukasoppermann** [comment]
Did you add the `VerifiesUsers` trait, `Jrean\UserVerification\Traits\VerifiesUsers` to your RegisterController?

**Comment by kinnedev** [comment]
Im an idiot....


Thank You

**Comment by lukasoppermann** [comment]
No worries, happens to all of us some times. Good that it was easy to solve. Cheers.
