### ISSUE TITLE
user is still able to login without email verification

### ISSUE THREAD

**Issue by bigoper** [jrean/laravel-user-verification#80]
Hey All,

1. I'm using a clean installation of laravel 5.3.
2. User can register to the systems
3. Emails are being sent as usual.
4. User can Login to the system without authenticating his email address...

I don't know how to force the user to authenticate his email (activation link is sent)
- verified = 1
- verification_token = null

he can login without verifying his email.

please advise.

thanks,
avi

**Comment by lukasoppermann** [comment]
Hey, prohibiting login without a verified email is not part of this package. You need to implement this behavior yourself. 

It's not included because not everybody actually needs this. However if you build a way that lets one activate this behavior via the config @jrean might merge a PR.

**Comment by bigoper** [comment]
Hey  lukasoppermann,

Thank you for the fast and informative reply :)
Can you please help me with something?
1. How do I use the 'isVerified' ? (what do I need to 'use' and the function usage)

Thanks!!

**Comment by lukasoppermann** [comment]
Hey @bigoper,

sure, to use the isVerified method you need to add the `Jrean\UserVerification\Traits\UserVerification` trait to your user model.

e.g.

```php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Jrean\UserVerification\Traits\UserVerification;

class User extends Authenticatable
{
    use Notifiable, UserVerification;
```

Now whenever you have an instance of a user model you can use it like so:

```php
$user = User::first();

if($user->isVerified()){
  echo "welcome";
}else{
  echo "Please verify your email.";
}

```

**Comment by bigoper** [comment]
Hey @lukasoppermann ,

I'm trying to use it my HomeController.
[http://vpaste.net/Td2rS]
I'm getting the following error:
[http://vpaste.net/fdoEt]

Thanks!!

**Comment by bigoper** [comment]
Whoops, my bad.
Fixed it :)

I was doing it all wrong ...
Pasted the code in the Use Model, and now I'm able to use it in the HomeController.

Thanks for everything!
