### ISSUE TITLE
Email from "address" can not be overwritten

### ISSUE THREAD

**Issue by bigoper** [jrean/laravel-user-verification#83]
Hey All,

**When using:**
    UserVerification::generate($user);
    UserVerification::send($user, 'IDX 2.0 - Email verification');
**and:**
    'from' => [
        'address' => 'services@example.com',
        'name' => 'IDX 2.0 SERVICES',
    ],

When receiving the email, it still looks like they are sent from the "address" that is configured in the account, and not the one from the from->address (config/mail.php).

How can I over write that?

Thanks,
Avi

**Comment by jrean** [comment]
Hi,

Not sure to understand you issue.
E-Mails are sent to registered users (recipients). So the package uses the user e-mail as the recipient.
By default for the "sender", the package will use the `address` and `name` keys values found into the `config/mail.php` file.

If you want to override this behaviour and as stated into the documentation you can use the following parameters:

```PHP
send(AuthenticatableContract $user, $subject = null, $from = null, $name = null)
```

> This package provides a method to send an e-mail with a link containing the verification token.
send(AuthenticatableContract $user, $subject = null, $from = null, $name = null)
By default the package will use the from and name values defined into the config/mail.php file:
'from' => ['address' => '', 'name' => ''],
If you want to override the values, simply set the $from and (optional) $name parameters.

**Comment by bigoper** [comment]
Hey,

I tried. not working :(
Unable to change the from address, it's always using the default one.

Thanks again,
avi

**Comment by jrean** [comment]
Hi,

CAN you please provide the version of Laravel you use?

CAN you please provide your code sample calling the send(... method.

Thank you 

J.

**Comment by bigoper** [comment]
Hi,
1.  Laravel 5.3
2. The call:
$user =  \Auth::user();
        UserVerification::generate($user);
        UserVerification::send($user, trans('messages.verify_email_title'), null, trans('messages.verify_email_from'));
3. The mail.php config
   'from' => [
        'address' => 'test@example.com',
        'name' => 'TEST SERVICES',
    ],
4. Note
Emails are being sent using the account credentials that configured in the .env file.
And all emails  are being sent with "from" address equal to the mentioned account.

I wish all email to bent with a diff "from" address.

Thanks!

**Comment by jrean** [comment]
Hi,

In your previous message (before you edited it) the value passed as the 3rd argument to the send method was `null`.

You then edited with `test@gmail.com`.
Can you confirm it is still not working?
If it is not, I will reproduce and test later today.

Cheers

**Comment by jrean** [comment]
Hi,

The send method has 4 params.
- 1st is the user object.
- 2nd is custom email title
- 3rd is custom e-mail sender (the from)
- 4th is the custom e-mail sender name (the name)

Why do you put "null" has the 3rd parameter?!
You should put the custom e-mail address you wish as sender.

Jean

**Comment by bigoper** [comment]
Hey Jrean,

I can confirm that no matter the value I put into the "from", it is still using the email address that is in the SMTP account in the mail config file.

Thanks,
Avi.

If you wish, I can give you access to my DESKTOP to view it.

**Comment by bigoper** [comment]
I've just realized that no matter what GitHub Project/Library/Function/Else I use to send emails, it always uses that account... :(

**Comment by bigoper** [comment]
Hey,

You can CLOSE the ISSUE.

1. http://stackoverflow.com/questions/1332510/how-to-change-from-address-when-using-gmail-smtp-server
2. It's "google's fault".

Thanks again!
Avi
