### ISSUE TITLE
class IsVerified does not exist

### ISSUE THREAD

**Issue by Unyxos** [jrean/laravel-user-verification#85]
Hi,

I installed your bundle and edited all files as needed (I think) but I have this error : 
Class Yeslife\Http\Jrean\UserVerification\Middleware\IsVerified does not exist

Yeslife is the name of my app, i correclty added the necessary code to my Kernel.php, to my routes... and still this error

Have you any idea ?

**Comment by jrean** [comment]
Hi,
You shouldn't touch your kernel.php file. There is something wrong in your settings but I can't help more if you don't provide sample code.

Cheers

Jean

**Comment by Unyxos** [comment]
Ok, i just followed the steps on https://packagist.org/packages/jrean/laravel-user-verification and it looks there's something to edit in Kernel.php to use the default Middleware 

here's my routes/web.php : 
`<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')->name('email-verification.check');

//controle si le visiteur a bien validé son compte par le lien dans le mail envoyé à l'inscription
Route::group(['middleware' => ['web', 'isVerified']], function () {

    //controle si le visiteur est logué sinon le redirige vers page login
    Route::group(['middleware' => 'auth'], function () {
        // routes evenements
        Route::get('/tousevent', 'EventsController@affiche');
        Route::get('/event', 'EventsController@index');
        Route::get('/event/create', 'EventsController@create');
        Route::get('/event/{event}', 'EventsController@show')->name('event.show');
        Route::post('/event', 'EventsController@store');  //recuperer les données du formualire create et renvoie vers methode store
        Route::get('/event/{event}/edit', 'EventsController@edit')->name('event.edit');
        Route::put('/event/{event}', 'EventsController@update');
        //recuperation pour supprimer l'evenement
        Route::delete('/event/{event}', 'EventsController@remove');

        //route comments
        Route::resource('comment', 'CommentsController');
        Route::get('comment/{eventid}/createCom', 'CommentsController@createCom')->name('comment.createCom');

        Route::post('/participationevent', 'ParticipationController@store')->name('participation.store');
        Route::delete('/participationevent/{part}', 'ParticipationController@remove');
        //route profils
        Route::get('/mon-profil', 'ProfilController@index');
        Route::get('/mon-profil/modifier', 'ProfilController@viewEdit');
        Route::put('/mon-profil/modifier/password', 'ProfilController@changePassword');
        Route::put('/mon-profil/modifier/profil', 'ProfilController@changeProfil');
        Route::get('/mon-profil/modifier/delete', 'ProfilController@delAccount');

        //route admin
        Route::get('/admin', 'AdminController@index');
        Route::get('/admin/members-list', 'AdminController@listMembers');
        Route::get('/admin/events-list', 'AdminController@listEvents');
        Route::get('/admin/interests-list', 'AdminController@listInterests');
        Route::get('/admin/events-list', 'AdminController@listEvents');
        Route::get('/admin/create-interest', 'AdminController@addInterest');
        Route::post('/admin/addinterest', 'AdminController@storeInterest');
        Route::get('/admin/delmember/{member}', 'AdminController@deleteMember');
        Route::get('/admin/delevent/{member}', 'AdminController@deleteEvent');
        Route::get('/admin/makeadmin/{member}', 'AdminController@makeMemberAdmin');
        Route::get('/admin/noadmin/{member}', 'AdminController@DontMakeMemberAdmin');

    });

    Route::get('/home', 'HomeController@index');
});

Auth::routes();`

Facade and Provider are defined in app.php, I edited my RegisterController.php as needed to include your bundle

**Comment by jrean** [comment]
Hi,
What you see on packagist is a clone of what you can see here on github. I'll check your code later Monday. What version of Laravel do you use? What version of the package do you use? Can you please try again and follow step by step what is described into the documentation. Everything is covered.

Cheers 

Jean

**Comment by jrean** [comment]
Hi, have you managed to follow the documentation and to make the package working?

**Comment by slowkow** [comment]
I'm setting up a fresh Laravel installation and running into the same problem.

Unfortunately, the documentation is not clear enough for me. I want any user who registers on my site to verify their email address before they can continue to any other page.

It seems to me that your documentation says we should edit the `app/Http/Kernel.php` file:

https://github.com/jrean/laravel-user-verification#default-middleware

I added the class, so I guess Laravel should know about the `IsVerified` class now. To my surprise, I get this error:

```
ReflectionException in Container.php line 749:
Class App\Http\Jrean\UserVerification\Middleware\IsVerified does not exist
```

Here is my `routes/web.php`:

```php
<?php

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['web', 'isVerified']], function () {

    Route::get('/home', 'HomeController@index');

});
```
