### ISSUE TITLE
Reflection Exception when using UserVerification::generate($user)

### ISSUE THREAD

**Issue by JosephELKHOURY** [jrean/laravel-user-verification#86]
Hello,

I followed the documentation step by step but I'm getting this error and can't find any solution to fix it:
ReflectionException in Container.php line 749:
Class user.verification does not exist

Do you know how can I fix this?

**Comment by jrean** [comment]
Hi,

Please share your code sample here.
Thank you 

Jean

**Comment by JosephELKHOURY** [comment]
Sure. I'm using it in my UsersController when users are registering using my API.
Here is my User class:

`
<?php

namespace app;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Jrean\UserVerification\Traits\UserVerification;
use App\Country;

class User extends Authenticatable
{
	use Notifiable;
	use EntrustUserTrait;
	use UserVerification;
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function country() {
        return $this->hasOne(Country::class, 'id', 'country_id');
    }
}
`

And here is my controller:
`
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;
use Auth;
use Hash;
use Tymon\JWTAuth\Facades\JWTAuth;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class UsersController extends Controller {

	use VerifiesUsers;

        public function store(Request $request) {
		$user = User::where('email', $request->email)->first();
		
		if (is_null($user)) {
			$user = new User;
			$user->email = $request->email;
			$user->password = Hash::make($request->password);
			$user->fbid = $request->fbid;
			$user->name = $request->name;
			$user->country_id = $request->country_id;
			$user->gender_id = $request->gender_id;
			$user->birth_date = $request->birth_date;
			
			$user->save();
			UserVerification::generate($user);
			UserVerification::send($user, 'Please verify your email address');
			
			if ($user->isVerified()) {
				$token = JWTAuth::fromUser($user);
				$user->country;
    			return response()->json(compact('user', 'token'));
			}
			else {
				return response()->json(array(
						'message' => 'Please verify your email address before proceeding',
						'user' => $user));
			}
		}
		
		return response()->json(array(
			'error' => 'Email already exists in our records',
			'user_id' => 0),
			409
		);
	}
}
`

**Comment by jrean** [comment]
Hi,

From your error trace:

```
at UserVerification::generate(null) in UsersController.php line 87
```

You are giving a `null` value to the `generate()` method.

**Comment by JosephELKHOURY** [comment]
Hmmm. I tried to replace the User creation with this method:

```
$user = User::create(['email' => $request->email, 
	              'password' => Hash::make($request->password), 
		      'fbid' => $request->fbid,
		      'name' => $request->name,
		      'country_id' => $request->country_id,				
                      'gender_id' => $request->gender_id,
	              'birth_date' => $request->birth_date]);
```

Now I'm getting a `<HTML></HTML>` response :( And it looks like there is an error but no error is displayed nor logged.

**Comment by jrean** [comment]
Hi,
I can't help you regarding how to create a user. Please read the Laravel documentation.
As mentioned within my previous message, you were giving a `null` value to the `generate()` method.

Try to go step by step with `var dump` or `dd()` and see what is going (or use a debugger if you have one).

**Comment by JosephELKHOURY** [comment]
I don't think the problem is with the user creation.
FYI, I just added this test before calling your functions:
```
if (!is_null($user)) {
    UserVerification::generate($user);
    UserVerification::send($user, 'Please verify your email address');
}
```
And I'm still getting an empty response. So the problem is from the library since the user object is not null.

**Comment by jrean** [comment]
And then doing so, what error do you receive?

**Comment by JosephELKHOURY** [comment]
And btw (something different), when running this command:
```
php artisan vendor:publish --provider="Jrean\UserVerification\UserVerificationServiceProvider" --tag="views"
```
I get this:
```
Nothing to publish for tag [views].
```

**Comment by jrean** [comment]
What version of Laravel + Package + Php are you using. Thanks

**Comment by JosephELKHOURY** [comment]
Laravel: 5.3.24
Php: PHP 5.6.28-1~dotdeb+zts+7.1
And "jrean/laravel-user-verification": "^3.0"

**Comment by jrean** [comment]
I will try to reproduce tomorrow. Can you please remove the package with composer and try to reinstall. Almost 10k downloads and never had the issue you encounters. Thank you for the feedback. Curious to find out what/why

**Comment by JosephELKHOURY** [comment]
I think I'm gonna kill myself. I removed the package, installed it again and still having the same issue!! This is driving me crazy :(

**Comment by moraya-re** [comment]
@JosephELKHOURY Did you resolved the issue? Cause I'm having the same issue.

**Comment by JosephELKHOURY** [comment]
Hey, no :(
I finally ended up creating my own functions.

**Comment by bab55z** [comment]
I had same problem follow these steps : 

-Stop `php artisan serve` if runing
-Run `php artisant config:cache` (to clear and refresh the config cache)
-Run `php artisan cache:clear` (to clear the laravel cache)
