### ISSUE TITLE
Add `web` Middleware To Routes?

### ISSUE THREAD

**Issue by zschuessler** [jrean/laravel-user-verification#88]
[Routes ](https://github.com/jrean/laravel-user-verification/blob/master/src/routes.php) do not currently use any middleware.

A common use case for this package is to extend the view templates and create extra functionality involving users. Without using the `web` middleware, the session data and other bootstrapped info is not available in view templates.

Is this by design? I ended up overriding routes in my own service provider to add the middleware, which is easy enough to do. But was curious if this was an intentional design decision.

Thanks for the amazing work on the package!

P.S. - Here is my extended code for reference:

```php
// Override user verification routes to include web middleware
        Route::group(
            [
                'middleware' => 'web'
            ],
            function () {
                Route::get(
                    'email-verification/error',
                    'App\Http\Controllers\Auth\RegisterController@getVerificationError'
                )->name('email-verification.error');

                Route::get(
                    'email-verification/check/{token}',
                    'App\Http\Controllers\Auth\RegisterController@getVerification'
                )->name('email-verification.check');

                Route::get(
                    'email-verification/resend',
                    'App\Http\Controllers\Auth\RegisterController@getResendVerification'
                )->name('email-verification.resend');
            }
        );
```

**Comment by jrean** [comment]
Hey @zschuessler thank you for the great feedback!
Do you suggest the `web` middleware should by default wrap the package routes?

**Comment by zschuessler** [comment]
I think so! That way we can easily access the Auth methods in the view templates. (eg `Auth::user()` to get current user)

**Comment by BryanYeh** [comment]
I think so too. I overwrote `getVerification(Request $request, $token)` to redirect with a message after verifying the email, but the redirect did not contain the message. unless the web middleware group was added to the routes.

**Comment by jrean** [comment]
@zschuessler @BryanYeh 
https://github.com/jrean/laravel-user-verification/releases/tag/v4.1.1
