### ISSUE TITLE
generate token, should be the user's encrypted email?

### ISSUE THREAD

**Issue by damarev** [jrean/laravel-user-verification#9]
Just a suggestion, i think generated token/code should be random and fixed length:
```
    protected function generateToken($email)
    {
        return sha1(microtime() . Crypt::encrypt($email));
    }
```

Now, Crypt::encrypt($email) returns a string of 272 characters from a 40 characters email, exceeding the 255 limit of the database migration.

Would you consider a PR?
Thank you for this nice laravel package.

**Comment by jrean** [comment]
@damarev thank you for the feedback.
https://github.com/jrean/laravel-user-verification/releases/tag/v2.2.0
