### ISSUE TITLE
Jrean\UserVerification\Traits\UserVerification

### ISSUE THREAD

**Issue by properius** [jrean/laravel-user-verification#90]
If I add UserVerification trait to the User model I start getting:

`Symfony\Component\Debug\Exception\FatalErrorException: Cannot use Jrean\UserVerification\Facades\UserVerification as UserVerification because the name is already in use in /my_project/vendor/jrean/laravel-user-verification/src/Traits/VerifiesUsers.php:11
`

Without the Jrean\UserVerification\Traits\UserVerification trait in the User model it works when I access any route.

Is anybody else getting this?

**Comment by jrean** [comment]
Hi,
Can you please share your code?

Thanks

**Comment by properius** [comment]
User:

```
use Jrean\UserVerification\Traits\UserVerification;
use Laravel\Spark\CanJoinTeams;
use Laravel\Spark\User as SparkUser;

class User extends SparkUser
{
    use UserVerification;
    use CanJoinTeams;
```

If `use CanJoinTeams;` is included it throws the exception. If I comment it out it works. Even `php artisan optimize` throws the exception.

Controller:

```
use Jrean\UserVerification\Facades\UserVerification;
use Jrean\UserVerification\Traits\VerifiesUsers;

class AppController extends Controller
{
    use VerifiesUsers;

```

**Comment by wayne5w** [comment]
Getting the same problem when I run tests using phpunit.

**Comment by jrean** [comment]
I need to investigate.
Can you please be kind and give me the steps to reproduce as well as your Laravel version + PHP version + Package version.

Thanks

**Comment by properius** [comment]
I have:

- Laravel: 5.3.26
- PHP: 7.0.11
- Package: 3.0

It might be a name clash since there is a facade named UserVerification and a trait with the same name.

**Comment by jrean** [comment]
@properius,

You are using Spark right? Can you search into your source if you find other occurence of `UserVerification`?

Thank you

**Comment by properius** [comment]
None found.

**Comment by wayne5w** [comment]
No spark here. Laravel 5.3 and PHP 7.

**Comment by jrean** [comment]
Please read my last comment

https://github.com/jrean/laravel-user-verification/issues/93

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.19
