### ISSUE TITLE
Hardcoded App name breaks things

### ISSUE THREAD

**Issue by sburina** [jrean/laravel-user-verification#92]
Hi!

After changing the app name from default App to anything else, routes don't work any more since the namespace is hardcoded in this package's routes.php.

**Comment by jrean** [comment]
Hi,
As described into the documentation, you can declare your own routes. It will override what the packages offers and should solve your issue.

**Comment by sburina** [comment]
Thank you! I've somehow missed that detail.
Sorry for the interrupt.. :)

**Comment by mlanser** [comment]
Hello, I know it's mentioned in the doc's, but I have a small suggestion for this:

if you replace the lines in routes.php as follows:
`Route::get('email-verification/error', app()->getNamespace().'Http\Controllers\Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', app()->getNamespace().'Http\Controllers\Auth\RegisterController@getVerification')->name('email-verification.check');
`

Then the AppName problem goes away and one only needs to declare new routes if one doesn't like the default routes at all.

Just a thought :)

Thanks ..
-martin.

**Comment by jrean** [comment]
Nice one Martin!
Thank you, I will implement it.

**Comment by mlanser** [comment]
Thanks! :)
