### ISSUE TITLE
Error: property of non-object

### ISSUE THREAD

**Issue by xparthx** [jrean/laravel-user-verification#93]
Hello,

I'm getting error: Attempt to assign property of non-object
which is here:
Line no 255 $user->table = $table;  File: UserVerification.php

I have dump $user to check and found it has all the users table field but it does't have "table" key, so that is why it throws this error.

Furthermore, I'm getting "Trying to get property of non-object" on line no 270 
if ($user->verified == true)  in that same file.

Again I checked $user, now this time issue is that it is an array not an object, so its throwing the error.

So are these bugs already in the package? Or if not that what possible causes it could be with my project? As far as I know I have done all the configuration correctly as mentioned in the documentation.

Thanks,
Parth vora

**Comment by jrean** [comment]
Hi,

Can you please share you controller code. What version of package + Laravel + php are you using?

Jean

**Comment by xparthx** [comment]
PHP version: 5.6.15
Laravel version: 5.3.22

Here is my controller:

`<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use Storage;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RegistersUsers;
use App\Http\Controllers\ImageThumbController;
use App\Notifications\SignupComplete;
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;
    use VerifiesUsers;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['getVerification', 'getVerificationError']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255|regex:/^[a-zA-Z\s]*$/',
            'username' => 'required|min:3|max:255|regex:/^[a-zA-Z0-9\s]*$/|unique:users',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required',
            'contact_no' => 'required|digits:12',
            'gender' => 'required|in:male,female',
            'country' => 'required',
            'hobbies' => 'required',
            'about_me' => 'required|min:6',
            'date_of_birth' => 'date',
            'avatar' => 'required|image',
            ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        $avatars_org_dir = 'public/avatars/origional';
        Storage::makeDirectory($avatars_org_dir);

        if($avatar_file = $data['avatar']->store($avatars_org_dir)) // Upload avatar
        {
            $org_avatar_source = str_replace ('public', 'storage', $avatar_file);

             $user = User::create([
                'name' => $data['name'],
                'username' => $data['username'],
                'email' => $data['email'],
                'password' => bcrypt($data['password']),
                'contact_no' => $data['contact_no'],
                'gender' => $data['gender'],
                'country' => $data['country'],
                'hobbies' => $data['hobbies'],
                'about_me' => $data['about_me'],
                'date_of_birth' => $data['date_of_birth'],
                'avatar' => $org_avatar_source,
                'user_type' => 'blogger',
                'social_id' => NULL,
                'registration_type' => 'conventional',
                'deleted_at' => NULL
            ]);  

            if($user) {
                UserVerification::generate($user);
                UserVerification::send($user, 'E-mail verification');

                $user->notify(new SignupComplete($user));
                return $user;
            }  else {
                return false;
            }
        }
    }
}`

**Comment by jrean** [comment]
Hi,

Fresh install of Laravel 5.3:

- `composer require jrean/laravel-user-verification`
- Migrate the database migration for the package to update your database structure

Edit your `config/app.php` file:

```
    'providers' => [
        ...
        Jrean\UserVerification\UserVerificationServiceProvider::class,
        ....
    ],

    'aliases' => [
         ...
        'UserVerification' => Jrean\UserVerification\Facades\UserVerification::class,
        ....
    ],
```

Edit your `app/User.php` model file:
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Jrean\UserVerification\Traits\UserVerification;

class User extends Authenticatable
{
    use Notifiable;
    use UserVerification;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

Edit your `app/Http/Controllers/Auth/RegisterController.php` file:

```
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;

use Illuminate\Http\Request;
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    use VerifiesUsers;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest', ['except' => ['getVerification', 'getVerificationError']]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

    /**
     * Handle a registration request for the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        $user = $this->create($request->all());
        $this->guard()->login($user);

        UserVerification::generate($user);
        UserVerification::send($user, 'My Custom E-mail Subject');

        return redirect($this->redirectPath());
    }
}
```

Edit your `routes/web.php` file:

```
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('verification/error', 'Auth\RegisterController@getVerificationError');
Route::get('verification/{token}', 'Auth\RegisterController@getVerification');

Auth::routes();

Route::get('/home', 'HomeController@index');
```

Out of the box the package is doing it's job and working properly. I simply followd the documentation.

Extra:

Edit your `app/Http/Controllers/HomeController.php` file:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        dd(auth()->user()->isVerified());
        return view('home');
    }
}
```

Visiting the `index()` route will output `true` if your user is logged AND verified.

Please read step by step and carefuly the documentation.

**Comment by xparthx** [comment]
Hello,

Sorry man, but I'm in trouble again. I have followed each of the steps correctly as you mentioned above and read the documentation 5 times. When I click on the verification link from the email, I'm getting:

"Trying to get property of non-object" on line no 270.

**if ($user->verified == true)** 

I dump the $user variable. Issue is that it is an array not an **object**, so its throwing the error.

Here's my whole controller:

```
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use Storage;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RegistersUsers;
use App\Http\Controllers\ImageThumbController;
use App\Notifications\SignupComplete;
use Illuminate\Http\Request;
use Illuminate\Auth\Events\Registered;
use Jrean\UserVerification\Traits\VerifiesUsers;
use Jrean\UserVerification\Facades\UserVerification;

class RegisterController extends Controller
{
    use RegistersUsers;
    use VerifiesUsers;
    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware('guest', ['getVerification', 'getVerificationError']);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255|regex:/^[a-zA-Z\s]*$/',
            'username' => 'required|min:3|max:255|regex:/^[a-zA-Z0-9\s]*$/|unique:users',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required',
            'contact_no' => 'digits:10',
            'gender' => 'in:male,female',
            'country' => '',
            'hobbies' => '',
            'about_me' => 'min:6',
            'date_of_birth' => 'date',
            'avatar' => 'image',
            ]);
    }

    public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        event(new Registered($user = $this->create($request->all())));

        return $this->registered($request, $user)
            ?: redirect($this->redirectPath());
    }

    protected function create(array $data)
    {
        $org_avatar_source = '';
        $avatars_org_dir = 'public/avatars/origional';
        Storage::makeDirectory($avatars_org_dir);

        if (isset($data['avatar'])) {
            if($avatar_file = $data['avatar']->store($avatars_org_dir)) // Upload avatar
            {
                $org_avatar_source = str_replace ('public', 'storage', $avatar_file);
            }
        }

        $user = User::create([
            'name' => $data['name'],
            'username' => $data['username'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'contact_no' => isset($data['contact_no']) ? $data['contact_no'] : '',
            'gender' => isset($data['gender']) ? $data['gender'] : '',
            'country' => isset($data['country']) ? $data['country'] : '',
            'hobbies' => isset($data['hobbies']) ? $data['hobbies'] : '',
            'about_me' => isset($data['about_me']) ? $data['about_me'] : '',
            'date_of_birth' => isset($data['date_of_birth']) ? $data['date_of_birth'] : '',
            'avatar' => $org_avatar_source,
            'user_type' => 'blogger',
            'social_id' => NULL,
            'registration_type' => 'conventional',
            'deleted_at' => NULL
        ]);  

        if($user) {
            UserVerification::generate($user);
            UserVerification::sendQueue($user, 'E-mail verification');

            $user->notify(new SignupComplete($user));
            return $user;
        }  else {
            return false;
        }
    }
}
```
Here's my whole model:

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Laravel\Cashier\Billable;
use Carbon\Carbon;
use Jrean\UserVerification\Traits\UserVerification;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class User extends Eloquent implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Notifiable, Authenticatable, Authorizable, CanResetPassword, SoftDeletes, Billable, UserVerification;

    protected $fillable = [
        'name', 'username', 'email', 'password', 'contact_no', 'gender', 'country', 
        'hobbies', 'about_me', 'date_of_birth', 'avatar', 'user_type', 
        'social_id', 'registration_type', 'slack_webhook_url', 'deleted_at'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'hobbies' => 'array',
    ];

    protected $dates = [
        'date_of_birth',
        'deleted_at'
    ];

    protected $dateFormat = 'd-m-Y H:i:s';

    public function isAdmin()
    {
        return ($this->user_type == 'admin') ? true : false;
    }
    
    public function getDateOfBirthAttribute($value)
    {
        return Carbon::parse($value)->format('d-m-Y H:i:s');
    }

    public function setDateOfBirthAttribute($value)
    {
        $this->attributes['date_of_birth'] = Carbon::parse($value)->format('d-m-Y H:i:s');
    } 
    
    public function blogs() {
        return $this->hasMany('App\Blog');
    }
    
    public function comments() {
        return $this->hasMany('App\Comment');
    }

    public function routeNotificationForSlack()
    {
        return $this->slack_webhook_url;
    }

    public function routeNotificationForNexmo()
    {
        return $this->contact_no;
    }
}
```

I'm fine with default routes, so no need to override. 

What is the issue now? Is some other trait overriding $user?

Thanks,
Parth vora

**Comment by BryanYeh** [comment]
Maybe this is causing it? (just comparing files) your register controller:
````
public function __construct()
{
    $this->middleware('guest', ['getVerification', 'getVerificationError']);
}
````
is not like the example:
````
public function __construct()
{
    $this->middleware('guest', ['except' => ['getVerification', 'getVerificationError']]);
}
````

**Comment by jrean** [comment]
I'm more concerned about your `$user` returned as an array instead of an object.

Internally when you click on the verification link it will call the verification method from the trait calling itself several methods such as the one to find/fetch the user to verify.
This method is relying on Laravel...

```
/**
     * Get the user by e-mail.
     *
     * @param  string  $email
     * @param  string  $table
     * @return stdClass
     *
     * @throws \Jrean\UserVerification\Exceptions\UserNotFoundException
     */
    protected function getUserByEmail($email, $table)
    {
        $user = DB::table($table)
            ->where('email', $email)
            ->first();

        if ($user === null) {
            throw new UserNotFoundException();
        }

        $user->table = $table;

        return $user;
    }
```

So honestly I don't know what you did.
Can you please simply try to install and run the package on a side Laravel project so you can play with it and understand step by step how it works?
Again following the documentation and without changing anything it should work out of the box.

Question: Using MongoDb, performing a `$users = User::all();` is returning a collection right? Performing a `$users->first();' is returning a User object right? (Because in your case you say it returns and array)

**Comment by jrean** [comment]
Following my previous message and the questions can you please tell me what is returned by:

```
        $user = DB::table($table)
            ->where('email', $email)
            ->first();
```

Where $table is your User table name.

Run that code in a test route just to check the output. Thanks

**Comment by xparthx** [comment]
Hey @jrean 

I have run below code on a separate route:

```
$user = DB::table($table)
            ->where('email', $email)
            ->first();
```

It returned an array and not an object.

Looks like MongoDB package casting it to an array.

**Comment by jrean** [comment]
I'm with a limited connection until tomorrow so I can't help much. At least you know why it doesn't work. On my side I will see how I could handle this situation refactoring the code. On your side check if you can define the returned type in the Laravel Mdb package you use.

**Comment by jrean** [comment]
Can you please run as well the 2 other queries I asked you to run in the previous message and share the returned value type. Thank you

**Comment by xparthx** [comment]
Hello,

I have setup new Laravel 5.3 with MySQL.

I have run below code on both, my current project(which uses MongoDB) and fresh Laravel. I got the same result i.e a collection

```
$users = App\User::all();
dd($users);
```

However for the following I got the different result on both setup.

```
$user = DB::table('users')
            ->where('email', 'xxx@xxx.com')
            ->first();
dd($user);
```

Laravel with MongoDB - Array
Laravel with MySQL - stdClass Object

I'm doing some investigation on why I'm getting different return type with that MongoDB package. Will let you know if I get anything.

Thanks,
Parth Vora

**Comment by jrean** [comment]
Thanks. The package is currently built to deal with a stdclass returned. Managing an array returned is easy to implement if not possible to change from mongo. However updating the db will need more steps as package should know if it's mongo or not...
Thanks

**Comment by xparthx** [comment]
Hello,

To be 100% sure, I have setup two fresh Laravel 5.3, one with MySQL and another with MongoDB.

And run this same code on both:

```
$user = DB::table('users')
->where('email', 'xxx@yyy.com')
->first();
dd($user);
```

L5.3 with MySQL returns **stdClass Object** whereas L5.3 with MongoDB returns an **Array**. 

So, its MongoDB package which converts it and not my custom code.

BTW if we use **get()** instead of first(), then I got same result for both the setup. Thought it might help you.

Thanks,
Parth vora

**Comment by xparthx** [comment]
Hello @jrean 

I have raised this issue on both GitHub as well as Stackoverflow.

https://github.com/jenssegers/laravel-mongodb/issues/1059

http://stackoverflow.com/questions/41201228/first-returns-and-array-instead-of-stdclass-object-laravel-5-3-mongodb

Lets hope that someone has some solution, so we can use this package with Laravel which uses MongoDB.

In meantime, whenever you get some time, can you please check that how much changes required in this package to make it compatible with MongoDB.

Thanks,
Parth vora

**Comment by xparthx** [comment]
Hello @jrean 

Are you planing to make this package working with MongoDB?

Thanks,
Parth vora

**Comment by jrean** [comment]
Hi,
Yes.

**Comment by xparthx** [comment]
Hey man,

Any update on this? Can you please tell me when can I expect this?

Thanks in advance

**Comment by darvindom** [comment]
Hi,
For MongoDB just change in "UserVerification.php"
    /**
     * Get the user by e-mail.
     *
     * @param  string  $email
     * @param  string  $table
     * @return stdClass
     *
     * @throws \Jrean\UserVerification\Exceptions\UserNotFoundException
     */
    protected function getUserByEmail($email, $table)
    {
        $user = DB::table($table)
            ->where('email', $email)
            ->first();

        if ($user === null) {
            throw new UserNotFoundException();
        }
        $user = (object)$user;
        $user->table = $table;

        return $user;
    }
