### ISSUE TITLE
IsVerified can't protect api routes

### ISSUE THREAD

**Issue by osaris** [jrean/laravel-user-verification#97]
Hello,

I can't reject API call if user isn't verified by adding the middleware ``ìsVerified`` to my api routes because this line https://github.com/jrean/laravel-user-verification/blob/c798f804e1eaf9e11424b6dbca065af70ef619f1/src/Middleware/IsVerified.php#L25 fails ($request->user() is null in this case)

Regards

**Comment by jrean** [comment]
Hi @osaris 
https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.18

Is that fixing your issue?

**Comment by osaris** [comment]
Looking at your commit here https://github.com/jrean/laravel-user-verification/commit/2cdf8fe4f08487de62b9539c286163c0320cdd4d i think it won't fix my issue because there won't be error anymore but no check is done anymore in the case of an API call ?

**Comment by jrean** [comment]
So I don't understand your question neither your request.

What do you suggest? Please share your thoughts + code sample

**Comment by osaris** [comment]
Sorry I have no code sample but the problem is that API guard doesn't set $request->user. Your patch doesn't provide an alternative to check if the current $user is verified, it simply doesn't do the check if $user is null.

I wasn't able to find a good code to do check for both web/api guard (and custom user guard ?) user. But the problem is mentionned here for example : https://github.com/laravel/framework/issues/11782#issuecomment-202145183

**Comment by jrean** [comment]
Sorry I don't understand what is your issue then.
Feel free to provide more details or code sample :-)
