### ISSUE TITLE
Cannot use Jrean\UserVerification\Facades\UserVerification as UserVerification because the name is already in use

### ISSUE THREAD

**Issue by sharp33r** [jrean/laravel-user-verification#99]
hi again jrean
https://github.com/jrean/laravel-user-verification/issues/98#issuecomment-272691767
check this, it's post of sleepingowl admin developer, we investigated problem and he found solution

**Comment by jrean** [comment]
https://github.com/jrean/laravel-user-verification/issues/98#issuecomment-272699538
